//! Machine-checkable conformance vectors for the Lycan spec family.
//!
//! Sources of truth:
//!   docs/lycan/spec/graph-binary-format.md §15 "Conformance requirements"
//!   docs/lycan/spec/capsule-format.md     §8  "Conformance requirements"
//!
//! Every `.bin` under tests/fixtures/conformance/vectors/ is COMMITTED and
//! asserted byte-identical to what the generator below produces
//! (`committed_fixtures_match_generator`). CI runs against the committed
//! bytes. To refresh intentionally:
//!
//!   CONFORMANCE_REGENERATE=1 cargo test --release --test conformance_vectors regenerate_fixtures
//!
//! "conformance-v0.1-pins-CURRENT" marks assertions that pin CURRENT
//! (lenient / lenient-broken) decoder behavior that a future versioned spec
//! may tighten; flipping them MUST be a deliberate break.
//!
//! Grammar/learning vectors land later with their specs — the manifest
//! schema here (id/file/expectations/pins/notes + scenario-based non-byte
//! vectors) is designed to absorb them without restructuring.
//!
//! NOTE (capsule side, spec §6 / conformance req 6): NO signing vectors are
//! provided because NO signing exists anywhere in the pipeline — integrity is
//! SHA-256 + substring checks only. A manifest signature today MUST be
//! ignored; presence of signing vectors here in the future means signing was
//! added and this note is stale.

use std::path::{Path, PathBuf};

use serde_json::Value;
use sha2::{Digest, Sha256};

use syntra::capsule;
use syntra::graph::*;
use syntra::verifier;

/// graph-binary-format.md §2 — pinned directly (spec §15.1: no in-repo test
/// asserted these before this harness).
const MAGIC: [u8; 4] = [0x4C, 0x59, 0x43, 0x4E];
const FORMAT_VERSION: u8 = 5;

// ─────────────────────────────────────────────────────────────────────────
// Paths + manifest
// ─────────────────────────────────────────────────────────────────────────

fn fixtures_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("conformance")
}

fn manifest_path() -> PathBuf {
    fixtures_root().join("manifest.json")
}

/// The manifest is committed bytes; the generator rewrites it verbatim from
/// this constant so `committed_fixtures_match_generator` can pin it too.
const MANIFEST_JSON: &str = r#"{
  "schema": "lycan-conformance-v0.1",
  "comment": "Generated by tests/conformance_vectors.rs; regenerate with CONFORMANCE_REGENERATE=1 cargo test --release --test conformance_vectors regenerate_fixtures. decode/verify values: 'ok', 'skip', or 'err:<substring>'. Grammar/learning vectors are added with their specs.",
  "magic": [76, 89, 67, 78],
  "graph_format_version": 5,
  "vectors": [
    {
      "id": "valid-minimal-graph-v5",
      "file": "vectors/valid-minimal-graph-v5.bin",
      "expectations": {
        "decode": "ok",
        "verify": "ok",
        "reencode_byte_equal": true,
        "pins": { "nodes_len": 1, "edges_len": 0, "state_len": 0, "journal_len": 0 },
        "notes": "Minimal legal graph: one ConstInt node, header counts from live lengths, explicit zero state + journal length fields, flags 0, entry 0 (§2, §12)."
      }
    },
    {
      "id": "valid-with-strings",
      "file": "vectors/valid-with-strings.bin",
      "expectations": {
        "decode": "ok",
        "verify": "ok",
        "reencode_byte_equal": true,
        "pins": {
          "nodes_len": 3,
          "strings_lossy": [
            { "index": 0, "expected": "héllo — 世界" },
            { "index": 1, "expected": "\ufffd\ufffdA" },
            { "index": 2, "expected": "" }
          ]
        },
        "notes": "String table: UTF-8 entry, raw NON-UTF8 bytes [0xFF,0xFE,0x41] (raw bytes round-trip byte-exact; get_string surfaces them lossy UTF-8, §4), and a zero-length entry (legal empty string)."
      }
    },
    {
      "id": "valid-strategy-within-tolerance",
      "file": "vectors/valid-strategy-within-tolerance.bin",
      "expectations": {
        "decode": "ok",
        "verify": "ok",
        "reencode_byte_equal": true,
        "pins": {
          "nodes_len": 3,
          "node_fields": [
            { "node": 0, "op": "Strategy", "weight_kind": "Strategy", "contract": "WithinTolerance", "objective": "Reward", "operand_count": 2, "weight_count": 3, "bias": 2.0, "state_slot": 0, "annotation": 0 }
          ]
        },
        "notes": "Strategy producer convention (§13.3): contract WithinTolerance, WeightKind::Strategy, n=2 option weights 1/n PLUS trailing epsilon slot 1e-6 (len == operands + 1); pure NodeRef operands (§13.4 SameOutput-purity rule does not fire); exercises state_slot/annotation/activation round-trip."
      }
    },
    {
      "id": "valid-adaptive-choice",
      "file": "vectors/valid-adaptive-choice.bin",
      "expectations": {
        "decode": "ok",
        "verify": "ok",
        "reencode_byte_equal": true,
        "pins": {
          "nodes_len": 4,
          "node_fields": [
            { "node": 0, "op": "AdaptiveChoice", "weight_kind": "Adaptive", "contract": "None", "objective": "Confidence", "operand_count": 3, "weight_count": 3 }
          ]
        },
        "notes": "choice producer convention (§13.3): AdaptiveChoice, contract None, WeightKind::Adaptive, exactly n weights = 1/n (len == operands)."
      }
    },
    {
      "id": "valid-edges-gates",
      "file": "vectors/valid-edges-gates.bin",
      "expectations": {
        "decode": "ok",
        "verify": "ok",
        "reencode_byte_equal": true,
        "pins": { "edges_len": 3, "edge_gates": [null, 2, 0] },
        "notes": "Edge record (§8): ungated edge + gated edges (gate node ids in range; verifier edge/gate bounds pass)."
      }
    },
    {
      "id": "valid-with-state",
      "file": "vectors/valid-with-state.bin",
      "expectations": {
        "decode": "ok",
        "verify": "ok",
        "reencode_byte_equal": true,
        "pins": { "state_len": 4, "state": [1.5, -2.25, 0.0, 42.0] },
        "notes": "State section (§9): u32 length + f64 LE values, explicit length field always written (conforming encoder rule)."
      }
    },
    {
      "id": "valid-with-journal",
      "file": "vectors/valid-with-journal.bin",
      "expectations": {
        "decode": "ok",
        "verify": "ok",
        "reencode_byte_equal": true,
        "pins": {
          "journal_len": 4,
          "journal_fields": [
            { "entry": 0, "mutation": "WeightUpdate", "run_number": 1, "node_id": 0 },
            { "entry": 1, "mutation": "TypeSpecialized", "run_number": 2, "node_id": 0 },
            { "entry": 2, "mutation": "NodeSpawned", "run_number": 3, "node_id": 0 },
            { "entry": 3, "mutation": "EvolutionCompleted", "run_number": 4, "node_id": 0 }
          ]
        },
        "notes": "Journal section (§10): WeightUpdate MUST be written as the exact byte 0x00, never an arbitrary out-of-range byte (§14 mutation row); exact bytes 0,1,5,10 pin the map."
      }
    },
    {
      "id": "truncated-mid-node",
      "file": "vectors/truncated-mid-node.bin",
      "expectations": {
        "decode": "ok",
        "verify": "ok",
        "reencode_byte_equal": false,
        "pins": {
          "nodes_len": 2,
          "state_len": 0,
          "journal_len": 0,
          "node_fields": [
            { "node": 1, "op": "ConstNull", "operand_count": 0, "weight_count": 0, "bias": 0.0, "weight_kind": "Observational", "contract": "None", "objective": "None", "state_slot": null, "annotation": null }
          ]
        },
        "notes": "conformance-v0.1-pins-CURRENT (§14 primitive-reads-past-EOF + §9/§10 count-at-EOF): real header + full node 0 (43B) + first 5 bytes of node 1 (id+op) + 25 literal zero bytes, which the decoder consumes as node 1's operand_count..has_state fields. The file then ENDS: weight_kind, has_annotation, contract and objective are READ PAST EOF and return 0 (Observational / None / None) — the zero-padding corner itself; the state and journal length fields are likewise ABSENT and default to 0 via the pos>=len branch. Guard/leniency interaction: a genuine cut at EOF here would first trip the MIN_NODE_BYTES guard (2 nodes x 34 = 68 bytes needed, only 48 remain), so zero padding is the only way a mid-node truncation reaches this corner. Re-encoding re-emits the record section identically but appends the two missing length fields (114 vs 102 bytes) -> NOT byte-equal. A conforming encoder MUST NOT produce this file."
      }
    },
    {
      "id": "missing-journal-section",
      "file": "vectors/missing-journal-section.bin",
      "expectations": {
        "decode": "ok",
        "verify": "ok",
        "reencode_byte_equal": false,
        "pins": { "journal_len": 0 },
        "notes": "conformance-v0.1-pins-CURRENT (§10/§14 journal-count-at-EOF): encoder output for a 1-entry journal, journal count field (4B) + record (17B) removed. Decoder yields an EMPTY journal silently (count missing at EOF => 0); the original entry vanishes without error. Re-encode appends count 0 + nothing else: 4 extra bytes -> NOT byte-equal."
      }
    },
    {
      "id": "state-len-absent-at-eof",
      "file": "vectors/state-len-absent-at-eof.bin",
      "expectations": {
        "decode": "ok",
        "verify": "ok",
        "reencode_byte_equal": false,
        "pins": { "state_len": 0, "journal_len": 0 },
        "notes": "conformance-v0.1-pins-CURRENT (§9/§14 state-length-at-EOF): file ends exactly where the node/edge sections end; missing state length => 0, missing journal count => 0. Re-encode appends the two length fields: 8 extra bytes -> NOT byte-equal."
      }
    },
    {
      "id": "truncated-journal-mid-record",
      "file": "vectors/truncated-journal-mid-record.bin",
      "expectations": {
        "decode": "err:journal count 1 too large for input size: needs at least 17 bytes, have 8 remaining (header count out of bounds)",
        "verify": "skip",
        "reencode_byte_equal": false,
        "notes": "SPEC ERRATUM pinned against the working tree (spec §10/§14 claim 'loop breaks silently; short journal accepted'): journal count 1 is present but the file ends after the record's run_number (8 of 17 bytes) — the tree REJECTS. MIN_JOURNAL_BYTES is exactly the record size, so check_count always rejects a mid-record truncation before graph.rs:542's silent break can fire; that lenient corner is UNREACHABLE. A short journal decodes only when the count field is entirely absent (see missing-journal-section)."
      }
    },
    {
      "id": "enum-bytes-out-of-range",
      "file": "vectors/enum-bytes-out-of-range.bin",
      "expectations": {
        "decode": "ok",
        "verify": "ok",
        "reencode_byte_equal": false,
        "pins": {
          "nodes_len": 3,
          "journal_len": 2,
          "node_fields": [
            { "node": 0, "op": "AdaptiveChoice", "weight_kind": "Observational", "contract": "None", "objective": "None", "operand_count": 2, "weight_count": 2 },
            { "node": 1, "op": "ConstInt", "weight_kind": "Observational", "contract": "None", "objective": "None" },
            { "node": 2, "op": "ConstFloat", "weight_kind": "Observational", "contract": "None", "objective": "None" }
          ],
          "journal_fields": [
            { "entry": 0, "mutation": "WeightUpdate", "run_number": 7 },
            { "entry": 1, "mutation": "WeightUpdate", "run_number": 1 }
          ]
        },
        "notes": "conformance-v0.1-pins-CURRENT (§14 lenient enum coercion, spec §15.8): hand-assembled bytes — weight_kind 0x7F and 0x04 (WeightKind::Decision discriminant — NOT in the decode map, so even a legal encoder value for it round-trips to Observational), contract 0x09, objective 0x2A, journal mutation 0xEE — all DECODE (no error) to the documented defaults Observational/None/None/WeightUpdate. The out-of-range journal byte 0xEE is indistinguishable from the explicitly-written 0x00 in entry 1. Corrupt enum bytes silently change semantics; the verifier is blind to them (it checks semantics, not bytes). Re-encode normalizes all four fields to 0x00 -> NOT byte-equal; a future strictness change MUST flip these expectations as a versioned break."
      }
    },
    {
      "id": "strategy-bad-weights",
      "file": "vectors/strategy-bad-weights.bin",
      "expectations": {
        "decode": "ok",
        "verify": "err:node #0 Strategy: weights count 4 does not match operand count 2 (contract WithinTolerance requires 3)",
        "reencode_byte_equal": true,
        "notes": "Spec §13/§15.7: the BYTES decode cleanly (no in-repo test could catch this at decode time); verifier rule 13 rejects the epsilon-slot arity violation with the exact template. reencode byte-equal: true pins that the file is honest encoder output."
      }
    },
    {
      "id": "adaptive-bad-weights",
      "file": "vectors/adaptive-bad-weights.bin",
      "expectations": {
        "decode": "ok",
        "verify": "err:node #0 AdaptiveChoice: weights count 4 does not match operand count 3 (contract None requires 3)",
        "reencode_byte_equal": true,
        "notes": "Spec §13/§15.7 None-contract half: AdaptiveChoice with len(weights) != operands.len() rejected by verifier rule 13 (executor would index results out of bounds)."
      }
    },
    {
      "id": "guard-ceiling-counts",
      "file": "vectors/guard-ceiling-counts.bin",
      "expectations": {
        "decode": "err:node count 4294967295 exceeds maximum 1000000 (header count too large; possible malicious or corrupt .lyc)",
        "verify": "skip",
        "reencode_byte_equal": false,
        "notes": "§11 template 1: header node_count 0xFFFFFFFF is rejected by check_count BEFORE any Vec::with_capacity. No allocation / no panic — this test completing quickly IS the no-OOM proof (§15.4)."
      }
    },
    {
      "id": "guard-ceiling-edges",
      "file": "vectors/guard-ceiling-edges.bin",
      "expectations": {
        "decode": "err:edge count 4294967295 exceeds maximum 4000000 (header count too large; possible malicious or corrupt .lyc)",
        "verify": "skip",
        "reencode_byte_equal": false,
        "notes": "§11 template 1, edge label (check order string -> node -> edge pinned via node_count=0)."
      }
    },
    {
      "id": "count-too-big-for-input",
      "file": "vectors/count-too-big-for-input.bin",
      "expectations": {
        "decode": "err:node count 100 too large for input size: needs at least 3400 bytes, have 32 remaining (header count out of bounds)",
        "verify": "skip",
        "reencode_byte_equal": false,
        "notes": "§11 template 2: node_count below the hard ceiling but impossible for the remaining buffer — 100 x MIN_NODE_BYTES(34) vs 32 bytes present (file is 61 bytes)."
      }
    },
    {
      "id": "unknown-opcode-0xBB",
      "file": "vectors/unknown-opcode-0xBB.bin",
      "expectations": {
        "decode": "err:unknown opcode 0xBB",
        "verify": "skip",
        "reencode_byte_equal": false,
        "notes": "§7/§15.5: opcode bytes NOT in the §7 table hard-fail; never coerced (contrast §14 enum leniency). Node section is zero-padded to satisfy the MIN_NODE_BYTES guard so the opcode check is actually reached."
      }
    },
    {
      "id": "unknown-operand-tag-0x77",
      "file": "vectors/unknown-operand-tag-0x77.bin",
      "expectations": {
        "decode": "err:unknown operand tag 0x77",
        "verify": "skip",
        "reencode_byte_equal": false,
        "notes": "§6/§15.5: unknown operand tag aborts the WHOLE decode (graph.rs:610); 0x77 collides with nothing in the tag table (0x75-0x7D are opcode bytes, not tags)."
      }
    },
    {
      "id": "bad-magic",
      "file": "vectors/bad-magic.bin",
      "expectations": {
        "decode": "err:invalid .lyc file: bad magic",
        "verify": "skip",
        "reencode_byte_equal": false,
        "notes": "§3/§15.1: prefix LYC! != LYCN. In the CLI this byte prefix is dispatched to the legacy AST decoder instead (graph spec §1)."
      }
    },
    {
      "id": "too-short-file",
      "file": "vectors/too-short-file.bin",
      "expectations": {
        "decode": "err:invalid .lyc file: bad magic",
        "verify": "skip",
        "reencode_byte_equal": false,
        "notes": "§15.1 second half: 3 bytes (< 5) rejected with the SAME bad-magic string, not a truncation error."
      }
    },
    {
      "id": "wrong-version-6",
      "file": "vectors/wrong-version-6.bin",
      "expectations": {
        "decode": "err:unsupported version 6",
        "verify": "skip",
        "reencode_byte_equal": false,
        "notes": "§3/§15.2: correct magic, version byte 0x06 — exact error template 'unsupported version {version}'; no negotiation, no forward-compat path."
      }
    },
    {
      "id": "string-table-overflow",
      "file": "vectors/string-table-overflow.bin",
      "expectations": {
        "decode": "err:string table overflow at pos 33, len 4294967295",
        "verify": "skip",
        "reencode_byte_equal": false,
        "notes": "§4/§15.6: string entry length prefix runs past the file — the one in-body bound error; MUST be produced, never replaced by truncation."
      }
    }
  ],
  "capsule_vectors": [
    {
      "id": "capsule-happy",
      "scenario": "create",
      "expectations": {
        "verify_capsule": "ok",
        "pins": {
          "program_identical": true,
          "files_exact": ["inspect.json", "journal.json", "manifest.json", "policy.json", "program.lyc"],
          "manifest_sha256_of_program": true,
          "manifest_contains": ["\"version\": \"0.1.0\"", "\"entry\": \"program.lyc\"", "\"inputs\": []", "\"outputs\": [\"stdout\"]", "\"created_by\": \"lycan 0.1.0\"", "\"format\": \"lycan-capsule-v1\""],
          "policy_contains": ["\"allow_stdout\": true", "\"allow_self_modify\": true", "\"max_execution_ms\": 30000", "\"max_memory_bytes\": 268435456"]
        },
        "notes": "Capsule spec §8 reqs 1-3 (file set + program byte-identity + manifest literal keys + §2.4 create-path policy defaults incl. both budgets) on a capsule created from valid-with-strings.bin (a Print-using graph -> stdout capability derived)."
      }
    },
    {
      "id": "capsule-tampered-program",
      "scenario": "tamper_program",
      "expectations": { "verify_capsule": "err:program.lyc hash mismatch (actual: " },
      "notes": "§8 req 5: one byte appended to program.lyc. CURRENT corner: the decoder IGNORES trailing bytes, so the graph still decodes+verifies — only the SHA-256 substring check catches it. conformance-v0.1-pins-CURRENT."
    },
    {
      "id": "capsule-tampered-inspect",
      "scenario": "tamper_inspect",
      "expectations": { "verify_capsule": "err:inspect.json hash mismatch (actual: " },
      "notes": "§8 req 5."
    },
    {
      "id": "capsule-missing-manifest",
      "scenario": "remove_manifest",
      "expectations": { "verify_capsule": "err:missing required file: manifest.json" },
      "notes": "§2.3 item 1."
    },
    {
      "id": "capsule-missing-policy",
      "scenario": "remove_policy",
      "expectations": { "verify_capsule": "err:missing required file: policy.json" },
      "notes": "§2.3 item 1."
    },
    {
      "id": "capsule-format-substring",
      "scenario": "corrupt_format_string",
      "expectations": { "verify_capsule": "err:manifest.json missing format field" },
      "notes": "§2.3 item 3 / §8 req 5 — conformance-v0.1-pins-CURRENT: the check is TWO substring tests over the raw manifest text ('\"format\"' AND 'lycan-capsule'), not a field parse; replacing only the format VALUE trips it. A consumer MUST NOT treat the substring test as a security property (§6)."
    },
    {
      "id": "capsule-policy-reformatted",
      "scenario": "reformat_policy_json",
      "expectations": { "verify_capsule": "err:graph uses stdout but policy does not allow it" },
      "notes": "§2.3 item 6 / §8 req 5 parenthetical — conformance-v0.1-pins-CURRENT: semantically IDENTICAL policy.json re-serialized compact (\"allow_stdout\":true, no space) breaks the formatting-sensitive substring check. Consumers SHOULD parse JSON; the substring form does not survive re-serialization."
    }
  ]
}
"#;

/// Load the committed manifest; if fixtures are missing entirely (fresh tree
/// before `add`, not CI), regenerate so the suite still runs — committed
/// bytes are always what CI asserts.
fn load_manifest() -> Value {
    let p = manifest_path();
    if !p.exists() {
        build_fixtures();
    }
    let text = std::fs::read_to_string(&p).expect("manifest.json readable");
    serde_json::from_str(&text).expect("manifest.json is valid JSON")
}

fn read_vector_file(entry: &Value) -> Vec<u8> {
    let path = fixtures_root().join(entry["file"].as_str().unwrap());
    if !path.exists() {
        build_fixtures();
    }
    std::fs::read(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()))
}

// ─────────────────────────────────────────────────────────────────────────
// Byte-level pins required up-front (spec §15.1: nothing in-repo did this)
// ─────────────────────────────────────────────────────────────────────────

#[test]
fn magic_and_format_version_constants_are_pinned() {
    // Direct pin on the constants themselves (they are private, so pin the
    // declarations textually…)...
    let src = include_str!("../src/graph.rs");
    assert!(
        src.contains("const MAGIC: [u8; 4] = [0x4C, 0x59, 0x43, 0x4E];"),
        "graph.rs MAGIC constant drifted from 4C 59 43 4E"
    );
    assert!(
        src.contains("const FORMAT_VERSION: u8 = 5;"),
        "graph.rs FORMAT_VERSION drifted from 5"
    );
    // …and behaviorally: the real encoder emits magic+version 5 at offsets 0..5.
    let head = NeuralGraph::new().to_bytes();
    assert_eq!(
        &head[..5],
        &[0x4C, 0x59, 0x43, 0x4E, 0x05],
        "encoder header prefix drifted"
    );
    // Manifest-level pin matches the harness constants.
    let m = load_manifest();
    assert_eq!(m["magic"].as_array().unwrap().len(), 4);
    let mmagic: Vec<u8> = m["magic"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as u8)
        .collect();
    assert_eq!(mmagic, MAGIC);
    assert_eq!(
        m["graph_format_version"].as_u64().unwrap() as u8,
        FORMAT_VERSION
    );
}

// ─────────────────────────────────────────────────────────────────────────
// Graph-vector harness
// ─────────────────────────────────────────────────────────────────────────

#[test]
fn conformance_vectors_graph_binary() {
    let manifest = load_manifest();
    let vectors = manifest["vectors"].as_array().unwrap();
    assert!(vectors.len() >= 16, "spec asks for 16+ graph vectors");
    for entry in vectors {
        run_graph_vector(entry);
    }
}

fn run_graph_vector(entry: &Value) {
    let id = entry["id"].as_str().unwrap();
    let exp = &entry["expectations"];
    let bytes = read_vector_file(entry);

    // §15.1/§15.2 direct byte pin on every vector that is supposed to be a
    // well-framed graph file.
    let decode_exp = exp["decode"].as_str().unwrap();
    if decode_exp == "ok" {
        assert!(bytes.len() >= 5, "{id}: too short to be a graph");
        assert_eq!(&bytes[..4], &MAGIC, "{id}: magic bytes drifted");
        assert_eq!(bytes[4], FORMAT_VERSION, "{id}: version byte drifted");
    }

    match NeuralGraph::from_bytes(&bytes) {
        Ok(g) => {
            assert_eq!(decode_exp, "ok", "{id}: decode unexpectedly succeeded");

            // verify expectation
            match exp["verify"].as_str().unwrap() {
                "ok" => {
                    if let Err(e) = verifier::verify(&g) {
                        panic!("{id}: verify failed: {e}");
                    }
                }
                "skip" => {}
                v => {
                    let err = format!("{}", verifier::verify(&g).unwrap_err());
                    let want = v.strip_prefix("err:").unwrap();
                    assert!(!want.is_empty(), "{id}: empty verify err expectation");
                    let want = v.strip_prefix("err:").unwrap();
                    assert!(
                        err.contains(want),
                        "{id}: verify error missing pinned substring\nwant: {want}\n got: {err}"
                    );
                }
            }

            // round-trip (§15.3 primary anti-drift check)
            let rt = g.to_bytes();
            if exp["reencode_byte_equal"].as_bool().unwrap() {
                assert_eq!(rt, bytes, "{id}: decode->encode not byte-equal (§15.3)");
            } else {
                assert_ne!(
                    rt, bytes,
                    "{id}: expected NON byte-equal re-encode (lenient-corner vector regressed to strict?)"
                );
            }

            if let Some(pins) = exp.get("pins") {
                apply_graph_pins(&g, pins, id);
            }
        }
        Err(e) => {
            let want = decode_exp
                .strip_prefix("err:")
                .unwrap_or_else(|| panic!("{id}: decode unexpectedly failed: {e}"));
            assert!(
                e == want || e.contains(want),
                "{id}: decode error mismatch\nwant substring: {want}\n got: {e}"
            );
        }
    }
}

/// Debug-name comparison for enum fields (OpCode/WeightKind/Contract/
/// Objective/MutationKind all derive Debug with the variant name).
fn dbg_name<T: std::fmt::Debug>(v: &T) -> String {
    format!("{v:?}")
}

fn opt_u32(v: &Value) -> Option<u32> {
    if v.is_null() {
        None
    } else {
        Some(v.as_u64().unwrap() as u32)
    }
}

fn apply_graph_pins(g: &NeuralGraph, pins: &Value, id: &str) {
    if let Some(v) = pins.get("nodes_len") {
        assert_eq!(
            g.nodes.len(),
            v.as_u64().unwrap() as usize,
            "{id}: nodes_len"
        );
    }
    if let Some(v) = pins.get("edges_len") {
        assert_eq!(
            g.edges.len(),
            v.as_u64().unwrap() as usize,
            "{id}: edges_len"
        );
    }
    if let Some(v) = pins.get("state_len") {
        assert_eq!(
            g.state.len(),
            v.as_u64().unwrap() as usize,
            "{id}: state_len"
        );
    }
    if let Some(v) = pins.get("journal_len") {
        assert_eq!(
            g.journal.len(),
            v.as_u64().unwrap() as usize,
            "{id}: journal_len"
        );
    }
    if let Some(v) = pins.get("state") {
        let want: Vec<f64> = v
            .as_array()
            .unwrap()
            .iter()
            .map(|x| x.as_f64().unwrap())
            .collect();
        assert_eq!(g.state, want, "{id}: state values");
    }
    if let Some(arr) = pins.get("edge_gates") {
        for (i, v) in arr.as_array().unwrap().iter().enumerate() {
            assert_eq!(g.edges[i].gate, opt_u32(v), "{id}: edge {i} gate");
        }
    }
    if let Some(arr) = pins.get("node_fields") {
        for item in arr.as_array().unwrap() {
            let n = &g.nodes[item["node"].as_u64().unwrap() as usize];
            let nidx = item["node"].as_u64().unwrap();
            if let Some(v) = item.get("op") {
                assert_eq!(dbg_name(&n.op), v.as_str().unwrap(), "{id}: node {nidx} op");
            }
            if let Some(v) = item.get("weight_kind") {
                assert_eq!(
                    dbg_name(&n.weight_kind),
                    v.as_str().unwrap(),
                    "{id}: node {nidx} weight_kind"
                );
            }
            if let Some(v) = item.get("contract") {
                assert_eq!(
                    dbg_name(&n.contract),
                    v.as_str().unwrap(),
                    "{id}: node {nidx} contract"
                );
            }
            if let Some(v) = item.get("objective") {
                assert_eq!(
                    dbg_name(&n.objective),
                    v.as_str().unwrap(),
                    "{id}: node {nidx} objective"
                );
            }
            if let Some(v) = item.get("operand_count") {
                assert_eq!(
                    n.operands.len(),
                    v.as_u64().unwrap() as usize,
                    "{id}: node {nidx} operand_count"
                );
            }
            if let Some(v) = item.get("weight_count") {
                assert_eq!(
                    n.weights.len(),
                    v.as_u64().unwrap() as usize,
                    "{id}: node {nidx} weight_count"
                );
            }
            if let Some(v) = item.get("bias") {
                assert_eq!(n.bias, v.as_f64().unwrap(), "{id}: node {nidx} bias");
            }
            if let Some(v) = item.get("state_slot") {
                assert_eq!(n.state_slot, opt_u32(v), "{id}: node {nidx} state_slot");
            }
            if let Some(v) = item.get("annotation") {
                assert_eq!(n.annotation, opt_u32(v), "{id}: node {nidx} annotation");
            }
        }
    }
    if let Some(arr) = pins.get("journal_fields") {
        for item in arr.as_array().unwrap() {
            let j = &g.journal[item["entry"].as_u64().unwrap() as usize];
            let jidx = item["entry"].as_u64().unwrap();
            if let Some(v) = item.get("mutation") {
                assert_eq!(
                    dbg_name(&j.mutation),
                    v.as_str().unwrap(),
                    "{id}: journal {jidx} mutation"
                );
            }
            if let Some(v) = item.get("run_number") {
                assert_eq!(
                    j.run_number,
                    v.as_u64().unwrap(),
                    "{id}: journal {jidx} run_number"
                );
            }
            if let Some(v) = item.get("node_id") {
                assert_eq!(
                    j.node_id,
                    v.as_u64().unwrap() as u32,
                    "{id}: journal {jidx} node_id"
                );
            }
        }
    }
    if let Some(arr) = pins.get("strings_lossy") {
        for item in arr.as_array().unwrap() {
            let idx = item["index"].as_u64().unwrap() as u32;
            assert_eq!(
                g.get_string(idx),
                item["expected"].as_str().unwrap(),
                "{id}: get_string({idx}) (lossy UTF-8 surface, §4)"
            );
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────
// Capsule-vector harness (files are directories, not bytes — built in temp
// dirs programmatically from committed fixture bytes)
// ─────────────────────────────────────────────────────────────────────────

struct TempDir(PathBuf);
impl TempDir {
    fn new(tag: &str) -> Self {
        let dir = std::env::temp_dir().join(format!(
            "lycan-conformance-{tag}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .subsec_nanos()
        ));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        Self(dir)
    }
    fn path(&self) -> &Path {
        &self.0
    }
}
impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

#[test]
fn conformance_vectors_capsule_containers() {
    let manifest = load_manifest();
    for entry in manifest["capsule_vectors"].as_array().unwrap() {
        run_capsule_vector(entry);
    }
}

fn run_capsule_vector(entry: &Value) {
    let id = entry["id"].as_str().unwrap();
    let scenario = entry["scenario"].as_str().unwrap();
    let exp = &entry["expectations"];
    let program_bytes = read_manifest_vector(&load_manifest(), "valid-with-strings");

    let tmp = TempDir::new(id);
    let lyc = tmp.path().join("base.lyc");
    std::fs::write(&lyc, &program_bytes).unwrap();
    let dir = tmp.path().join(format!("{id}.lycap"));
    capsule::create(
        &lyc.to_string_lossy(),
        &dir.to_string_lossy(),
        "conformance",
        "spec conformance vector",
        vec![],
    )
    .unwrap_or_else(|e| panic!("{id}: capsule create failed: {e}"));

    // scenario mutations (tamper surface = on-disk files post-create)
    match scenario {
        "create" => {}
        "tamper_program" => {
            append_file(&dir.join("program.lyc"), &[0x00]);
        }
        "tamper_inspect" => {
            append_file(&dir.join("inspect.json"), b"\n");
        }
        "remove_manifest" => {
            std::fs::remove_file(dir.join("manifest.json")).unwrap();
        }
        "remove_policy" => {
            std::fs::remove_file(dir.join("policy.json")).unwrap();
        }
        "corrupt_format_string" => {
            let m = dir.join("manifest.json");
            let text = std::fs::read_to_string(&m).unwrap();
            std::fs::write(&m, text.replace("lycan-capsule-v1", "no-such-format-v1")).unwrap();
        }
        "reformat_policy_json" => {
            let p = dir.join("policy.json");
            let v: Value = serde_json::from_str(&std::fs::read_to_string(&p).unwrap()).unwrap();
            // Semantically identical, compact serialization (no space after ':').
            std::fs::write(&p, serde_json::to_string(&v).unwrap()).unwrap();
        }
        other => panic!("{id}: unknown scenario {other}"),
    }

    let result = capsule::verify_capsule(&dir.to_string_lossy());
    match exp["verify_capsule"].as_str().unwrap() {
        "ok" => {
            result.unwrap_or_else(|e| panic!("{id}: verify_capsule unexpectedly failed: {e}"));
        }
        v => {
            let want = v.strip_prefix("err:").unwrap();
            let err = result
                .err()
                .unwrap_or_else(|| panic!("{id}: verify_capsule unexpectedly succeeded"));
            assert!(
                err.contains(want),
                "{id}: verify error missing pinned substring\nwant: {want}\n got: {err}"
            );
        }
    }

    if let Some(pins) = exp.get("pins") {
        apply_capsule_pins(&dir, pins, &program_bytes, id);
    }
}

fn read_manifest_vector(manifest: &Value, id: &str) -> Vec<u8> {
    let entry = manifest["vectors"]
        .as_array()
        .unwrap()
        .iter()
        .find(|v| v["id"].as_str() == Some(id))
        .unwrap_or_else(|| panic!("manifest vector {id} missing"));
    read_vector_file(entry)
}

fn append_file(path: &Path, bytes: &[u8]) {
    use std::io::Write;
    let mut f = std::fs::OpenOptions::new().append(true).open(path).unwrap();
    f.write_all(bytes).unwrap();
}

fn sha256_hex(bytes: &[u8]) -> String {
    let mut h = Sha256::new();
    h.update(bytes);
    h.finalize().iter().map(|b| format!("{b:02x}")).collect()
}

fn apply_capsule_pins(dir: &Path, pins: &Value, program_bytes: &[u8], id: &str) {
    if pins.get("program_identical").and_then(|v| v.as_bool()) == Some(true) {
        // §8 req 1: program.lyc byte-identical to the input
        assert_eq!(
            std::fs::read(dir.join("program.lyc")).unwrap(),
            program_bytes,
            "{id}: program.lyc not byte-identical to input"
        );
    }
    if let Some(files) = pins.get("files_exact") {
        // §8 req 1: exactly these five files under {name}.lycap/
        let mut got: Vec<String> = std::fs::read_dir(dir)
            .unwrap()
            .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
            .collect();
        got.sort();
        let want: Vec<String> = files
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap().to_string())
            .collect();
        assert_eq!(got, want, "{id}: capsule file set");
    }
    if pins
        .get("manifest_sha256_of_program")
        .and_then(|v| v.as_bool())
        == Some(true)
    {
        // §8 req 2: program_sha256 equals SHA-256 over the on-disk program bytes
        let manifest = std::fs::read_to_string(dir.join("manifest.json")).unwrap();
        let on_disk = std::fs::read(dir.join("program.lyc")).unwrap();
        assert!(
            manifest.contains(&sha256_hex(&on_disk)),
            "{id}: manifest program_sha256 does not match on-disk program.lyc"
        );
    }
    for key in ["manifest_contains", "policy_contains"] {
        if let Some(list) = pins.get(key) {
            let file = if key == "manifest_contains" {
                "manifest.json"
            } else {
                "policy.json"
            };
            let text = std::fs::read_to_string(dir.join(file)).unwrap();
            for want in list.as_array().unwrap() {
                let want = want.as_str().unwrap();
                assert!(text.contains(want), "{id}: {file} missing literal {want}");
            }
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────
// Fixture generator
// ─────────────────────────────────────────────────────────────────────────

/// Regenerate every committed fixture. Invoked only by `regenerate_fixtures`
/// (env-gated) or as a missing-file fallback; CI asserts the committed bytes.
fn build_fixtures() {
    let root = fixtures_root();
    std::fs::create_dir_all(root.join("vectors")).unwrap();
    std::fs::write(manifest_path(), MANIFEST_JSON).unwrap();
    let manifest: Value = serde_json::from_str(MANIFEST_JSON).unwrap();
    for entry in manifest["vectors"].as_array().unwrap() {
        let id = entry["id"].as_str().unwrap();
        let path = root.join(entry["file"].as_str().unwrap());
        std::fs::write(&path, fixture_bytes(id)).unwrap();
    }
}

#[test]
#[ignore = "fixture maintenance: run with CONFORMANCE_REGENERATE=1 to rewrite committed bytes"]
fn regenerate_fixtures() {
    if std::env::var("CONFORMANCE_REGENERATE").as_deref() != Ok("1") {
        // Ignored by default AND env-gated: an accidental `-- --ignored` run
        // must not silently rewrite committed conformance bytes.
        return;
    }
    build_fixtures();
}

#[test]
fn committed_fixtures_match_generator() {
    // Anti-drift (mirrors tests/fixture_drift.rs): committed bytes must equal
    // what the encoder-level generator expresses, so a src/ change that
    // alters the format trips a named vector, not silent fixture rot.
    let manifest = load_manifest();
    let mtext = std::fs::read_to_string(manifest_path()).unwrap();
    assert_eq!(mtext, MANIFEST_JSON, "manifest.json drifted from generator");
    for entry in manifest["vectors"].as_array().unwrap() {
        let id = entry["id"].as_str().unwrap();
        assert_eq!(
            read_vector_file(entry),
            fixture_bytes(id),
            "{id}: committed bytes drifted from generator"
        );
    }
}

// ── byte-builder helpers for HAND-ASSEMBLED (illegal / patched) vectors ──
// The legal vectors all come from REAL encoder calls (NeuralGraph::to_bytes);
// these exist only because a conforming encoder MUST NOT be able to emit the
// corrupt shapes the reject-lattice vectors need (§14: encoders MUST NOT
// produce lenient-corner files).

fn put_u32(b: &mut Vec<u8>, v: u32) {
    b.extend_from_slice(&v.to_le_bytes());
}
fn put_f64(b: &mut Vec<u8>, v: f64) {
    b.extend_from_slice(&v.to_le_bytes());
}
fn put_u64(b: &mut Vec<u8>, v: u64) {
    b.extend_from_slice(&v.to_le_bytes());
}
fn put_i64(b: &mut Vec<u8>, v: i64) {
    b.extend_from_slice(&v.to_le_bytes());
}

/// 29-byte header (graph spec §2). One argument per header field.
#[allow(clippy::too_many_arguments)]
fn put_header(
    b: &mut Vec<u8>,
    version: u8,
    nodes: u32,
    edges: u32,
    state_size: u32,
    strings: u32,
    flags: u32,
    entry: u32,
) {
    b.extend_from_slice(&MAGIC);
    b.push(version);
    put_u32(b, nodes);
    put_u32(b, edges);
    put_u32(b, state_size);
    put_u32(b, strings);
    put_u32(b, flags);
    put_u32(b, entry);
}

/// One node record with EXPLICIT enum bytes (§5), no state slot / annotation.
/// One argument per record field.
#[allow(clippy::too_many_arguments)]
fn put_raw_node(
    b: &mut Vec<u8>,
    id: u32,
    op: u8,
    operands: &[u8],
    operand_count: u32,
    weights: &[f64],
    bias: f64,
    wk: u8,
    contract: u8,
    objective: u8,
) {
    put_u32(b, id);
    b.push(op);
    put_u32(b, operand_count);
    b.extend_from_slice(operands);
    put_u32(b, weights.len() as u32);
    for w in weights {
        put_f64(b, *w);
    }
    put_f64(b, bias);
    put_u64(b, 0); // activation_count
    b.push(0); // has_state = false
    b.push(wk);
    b.push(0); // has_annotation = false
    b.push(contract);
    b.push(objective);
}

fn raw_noderef(id: u32) -> Vec<u8> {
    let mut o = vec![0x01u8];
    put_u32(&mut o, id);
    o
}
fn raw_int(v: i64) -> Vec<u8> {
    let mut o = vec![0x10u8];
    put_i64(&mut o, v);
    o
}
fn raw_float(v: f64) -> Vec<u8> {
    let mut o = vec![0x11u8];
    put_f64(&mut o, v);
    o
}

// ── legal graphs, real encoder ──

fn g_minimal() -> NeuralGraph {
    let mut g = NeuralGraph::new();
    g.add_node(
        OpCode::ConstInt,
        vec![Operand::Immediate(ImmValue::Int(42))],
    );
    g
}

fn g_with_strings() -> NeuralGraph {
    let mut g = NeuralGraph::new();
    let s_utf8 = g.intern_string("héllo — 世界");
    g.string_table.push(vec![0xFF, 0xFE, 0x41]); // raw non-UTF8 bytes, index 1
    let s_empty = g.intern_string(""); // empty entry, index 2
    let a = g.add_node(OpCode::ConstStr, vec![Operand::StringRef(s_utf8)]);
    let b = g.add_node(OpCode::ConstStr, vec![Operand::StringRef(1)]);
    let c = g.add_node(OpCode::Print, vec![Operand::StringRef(s_empty)]);
    g.add_edge(a, b, 1.0);
    g.add_edge(b, c, 0.5);
    g
}

fn g_strategy(good_weights: bool) -> NeuralGraph {
    let mut g = NeuralGraph::new();
    let ann = g.intern_string("choose-best");
    let s = g.add_node(
        OpCode::Strategy,
        vec![Operand::NodeRef(1), Operand::NodeRef(2)],
    );
    let c1 = g.add_node(OpCode::ConstInt, vec![Operand::Immediate(ImmValue::Int(1))]);
    let c2 = g.add_node(
        OpCode::ConstFloat,
        vec![Operand::Immediate(ImmValue::Float(2.5))],
    );
    {
        let n = &mut g.nodes[s as usize];
        n.weight_kind = WeightKind::Strategy;
        n.contract = Contract::WithinTolerance;
        n.objective = Objective::Reward;
        n.weights = if good_weights {
            vec![0.5, 0.5, 1e-6] // n options + trailing epsilon slot (§13.3)
        } else {
            vec![0.5, 0.5, 0.5, 1e-6] // arity violation for verifier rule 13
        };
        n.bias = 2.0;
        n.activation_count = 7;
        n.state_slot = Some(0);
        n.annotation = Some(ann);
    }
    g.add_edge(c1, s, 1.0);
    g.add_edge(c2, s, 1.0);
    g
}

fn g_adaptive(good_weights: bool) -> NeuralGraph {
    let mut g = NeuralGraph::new();
    g.intern_string("pick");
    let a = g.add_node(
        OpCode::AdaptiveChoice,
        vec![
            Operand::NodeRef(1),
            Operand::NodeRef(2),
            Operand::NodeRef(3),
        ],
    );
    let c1 = g.add_node(OpCode::ConstInt, vec![Operand::Immediate(ImmValue::Int(1))]);
    let c2 = g.add_node(OpCode::ConstInt, vec![Operand::Immediate(ImmValue::Int(2))]);
    let c3 = g.add_node(OpCode::ConstInt, vec![Operand::Immediate(ImmValue::Int(3))]);
    {
        let n = &mut g.nodes[a as usize];
        n.weight_kind = WeightKind::Adaptive;
        n.contract = Contract::None;
        n.objective = Objective::Confidence;
        n.weights = if good_weights {
            vec![1.0 / 3.0, 1.0 / 3.0, 1.0 / 3.0]
        } else {
            vec![0.25, 0.25, 0.25, 0.25] // 4 weights vs 3 operands
        };
        n.annotation = Some(0);
    }
    g.add_edge(c1, a, 1.0);
    g.add_edge(c2, a, 1.0);
    g.add_edge(c3, a, 1.0);
    g
}

fn g_edges_gates() -> NeuralGraph {
    let mut g = NeuralGraph::new();
    let a = g.add_node(OpCode::ConstInt, vec![Operand::Immediate(ImmValue::Int(1))]);
    let b = g.add_node(OpCode::ConstInt, vec![Operand::Immediate(ImmValue::Int(2))]);
    let c = g.add_node(
        OpCode::ConstBool,
        vec![Operand::Immediate(ImmValue::Bool(true))],
    );
    g.add_edge(a, b, 1.0);
    g.add_edge(a, b, 0.5);
    g.edges[1].gate = Some(2);
    g.add_edge(b, c, 0.25);
    g.edges[2].gate = Some(0);
    g
}

fn g_with_state() -> NeuralGraph {
    let mut g = g_minimal();
    g.state = vec![1.5, -2.25, 0.0, 42.0];
    g
}

fn g_journal_one() -> NeuralGraph {
    let mut g = g_minimal();
    g.journal.push(JournalEntry {
        run_number: 5,
        node_id: 0,
        mutation: MutationKind::TypeSpecialized,
        reason: 9,
    });
    g
}

fn g_with_journal() -> NeuralGraph {
    let mut g = g_minimal();
    g.journal = vec![
        JournalEntry {
            run_number: 1,
            node_id: 0,
            mutation: MutationKind::WeightUpdate,
            reason: 0,
        },
        JournalEntry {
            run_number: 2,
            node_id: 0,
            mutation: MutationKind::TypeSpecialized,
            reason: 0,
        },
        JournalEntry {
            run_number: 3,
            node_id: 0,
            mutation: MutationKind::NodeSpawned,
            reason: 0,
        },
        JournalEntry {
            run_number: 4,
            node_id: 0,
            mutation: MutationKind::EvolutionCompleted,
            reason: 0,
        },
    ];
    g
}

fn fixture_bytes(id: &str) -> Vec<u8> {
    match id {
        // ── legal shapes from REAL encoder calls ──
        "valid-minimal-graph-v5" => g_minimal().to_bytes(),
        "valid-with-strings" => g_with_strings().to_bytes(),
        "valid-strategy-within-tolerance" => g_strategy(true).to_bytes(),
        "valid-adaptive-choice" => g_adaptive(true).to_bytes(),
        "valid-edges-gates" => g_edges_gates().to_bytes(),
        "valid-with-state" => g_with_state().to_bytes(),
        "valid-with-journal" => g_with_journal().to_bytes(),
        "strategy-bad-weights" => g_strategy(false).to_bytes(),
        "adaptive-bad-weights" => g_adaptive(false).to_bytes(),

        // ── lenient-corner files: encoder output cut / zero-padded ──
        "truncated-mid-node" => {
            let mut g = NeuralGraph::new();
            g.add_node(
                OpCode::ConstInt,
                vec![Operand::Immediate(ImmValue::Int(42))],
            ); // 43-byte record
            g.add_node(OpCode::ConstNull, vec![]); // 34-byte record
            let full = g.to_bytes();
            assert_eq!(full.len(), 29 + 43 + 34 + 4 + 4);
            let mut v = full[..(29 + 43 + 5)].to_vec(); // header + node0 + node1 (id,op)
            v.extend_from_slice(&[0u8; 25]); // zeros = node1 operand_count..has_state
            assert_eq!(v.len(), 102);
            v
        }
        "missing-journal-section" => {
            let full = g_journal_one().to_bytes();
            full[..full.len() - 21].to_vec() // drop journal count (4) + record (17)
        }
        "state-len-absent-at-eof" => {
            let full = g_minimal().to_bytes();
            full[..full.len() - 8].to_vec() // drop state length (4) + journal count (4)
        }
        "truncated-journal-mid-record" => {
            let full = g_journal_one().to_bytes();
            // keep through the journal count + the record's run_number only
            let cut = full.len() - (17 - 8);
            full[..cut].to_vec()
        }

        // ── hand-assembled illegal / corrupt-enum shapes ──
        "enum-bytes-out-of-range" => {
            let mut b = Vec::new();
            put_header(&mut b, 5, 3, 0, 0, 0, 0, 0);
            // node 0: AdaptiveChoice, 2 operands, 2 weights — after coercion
            // contract=None the rule-13 arity (== operands) holds.
            let mut ops = raw_noderef(1);
            ops.extend(raw_noderef(2));
            put_raw_node(&mut b, 0, 0x44, &ops, 2, &[0.5, 0.5], 0.0, 0x7F, 0x09, 0x2A);
            // node 1: weight_kind 0x04 == WeightKind::Decision discriminant —
            // not in the decode map => coerced Observational.
            put_raw_node(&mut b, 1, 0x01, &raw_int(42), 1, &[], 1.0, 0x04, 0x00, 0x00);
            put_raw_node(
                &mut b,
                2,
                0x02,
                &raw_float(2.5),
                1,
                &[],
                2.0,
                0x00,
                0x00,
                0x00,
            );
            put_u32(&mut b, 0); // state len
            put_u32(&mut b, 2); // journal count
            put_u64(&mut b, 7);
            put_u32(&mut b, 0);
            b.push(0xEE); // out-of-range mutation => WeightUpdate
            put_u32(&mut b, 0);
            put_u64(&mut b, 1);
            put_u32(&mut b, 0);
            b.push(0x00); // explicit WeightUpdate — indistinguishable above
            put_u32(&mut b, 9);
            b
        }
        "guard-ceiling-counts" => {
            let mut b = Vec::new();
            put_header(&mut b, 5, 0xFFFF_FFFF, 0, 0, 0, 0, 0);
            b.extend_from_slice(&[0u8; 8]);
            b
        }
        "guard-ceiling-edges" => {
            let mut b = Vec::new();
            put_header(&mut b, 5, 0, 0xFFFF_FFFF, 0, 0, 0, 0);
            b.extend_from_slice(&[0u8; 8]);
            b
        }
        "count-too-big-for-input" => {
            let mut b = Vec::new();
            put_header(&mut b, 5, 100, 0, 0, 0, 0, 0);
            b.extend_from_slice(&[0u8; 32]); // 32 remaining < 100*34
            b
        }
        "unknown-opcode-0xBB" => {
            let mut b = Vec::new();
            put_header(&mut b, 5, 1, 0, 0, 0, 0, 0);
            put_u32(&mut b, 0); // id
            b.push(0xBB); // op — outside the §7 table (0x7E TypeOf is IN the table since 2026-09-08; do not use it here)
            b.extend_from_slice(&[0u8; 29]); // pad so the MIN_NODE_BYTES guard passes
            b
        }
        "unknown-operand-tag-0x77" => {
            let mut b = Vec::new();
            put_header(&mut b, 5, 1, 0, 0, 0, 0, 0);
            put_u32(&mut b, 0); // id
            b.push(0x01); // op ConstInt
            put_u32(&mut b, 1); // operand_count
            b.push(0x77); // tag — not in §6
            put_u32(&mut b, 0);
            b.extend_from_slice(&[0u8; 20]);
            b
        }
        "bad-magic" => {
            let mut b = b"LYC!".to_vec();
            b.extend_from_slice(&[0u8; 8]);
            b
        }
        "too-short-file" => b"LYC".to_vec(),
        "wrong-version-6" => {
            let mut b = Vec::new();
            put_header(&mut b, 6, 0, 0, 0, 0, 0, 0);
            b
        }
        "string-table-overflow" => {
            let mut b = Vec::new();
            put_header(&mut b, 5, 0, 0, 0, 1, 0, 0);
            put_u32(&mut b, 0xFFFF_FFFF); // entry length past EOF
            b.extend_from_slice(&[0u8; 4]);
            b
        }
        other => panic!("no fixture generator for vector {other}"),
    }
}
