//! Capability specifications, values, and the static registry.

#[derive(Debug, Clone, Copy)]
pub struct CapabilitySpec {
    pub name: &'static str,
    pub version: &'static str,
    pub package: &'static str,
    pub summary: &'static str,
    pub inputs: &'static [&'static str],
    pub output: &'static str,
    pub purity: Purity,
    pub deterministic: bool,
    pub effects: &'static [&'static str],
    pub cost: &'static str,
    pub failure: &'static str,
    pub safety: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Purity {
    Pure,
    ReadOnlyEffect,
    Effectful,
}

#[derive(Debug, Clone, PartialEq)]
pub enum CapValue {
    Int(i64),
    Float(f64),
    Str(String),
    Bool(bool),
    Null,
    Array(Vec<CapValue>),
}

impl CapValue {
    pub fn type_name(&self) -> &'static str {
        match self {
            CapValue::Int(_) => "int",
            CapValue::Float(_) => "float",
            CapValue::Str(_) => "str",
            CapValue::Bool(_) => "bool",
            CapValue::Null => "null",
            CapValue::Array(_) => "array",
        }
    }

    /// Convert from serde_json::Value (used by server for JSON input).
    pub fn from_json(v: &serde_json::Value) -> Self {
        match v {
            serde_json::Value::Null => CapValue::Null,
            serde_json::Value::Bool(b) => CapValue::Bool(*b),
            serde_json::Value::Number(n) => {
                if let Some(i) = n.as_i64() { CapValue::Int(i) }
                else { CapValue::Float(n.as_f64().unwrap_or(0.0)) }
            }
            serde_json::Value::String(s) => CapValue::Str(s.clone()),
            serde_json::Value::Array(a) => CapValue::Array(a.iter().map(Self::from_json).collect()),
            serde_json::Value::Object(o) => CapValue::Array(
                o.iter().map(|(k, v)| CapValue::Array(vec![
                    CapValue::Str(k.clone()),
                    Self::from_json(v),
                ])).collect()
            ),
        }
    }
}

pub const REGISTRY: &[CapabilitySpec] = &[
    CapabilitySpec {
        name: "runtime.capabilities",
        version: "1.0.0",
        package: "runtime",
        summary: "Return the names of capabilities available in this runtime.",
        inputs: &[],
        output: "array<string>",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "O(number_of_capabilities)",
        failure: "never for a valid runtime",
        safety: "introspection only",
    },
    CapabilitySpec {
        name: "runtime.input",
        version: "1.0.0",
        package: "runtime",
        summary: "Return the full JSON input injected via --input flag.",
        inputs: &[],
        output: "any",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "O(1)",
        failure: "returns null if no input was provided",
        safety: "read-only access to injected input",
    },
    CapabilitySpec {
        name: "runtime.inputGet",
        version: "1.0.0",
        package: "runtime",
        summary: "Access a nested field in the injected input by dot-path (e.g. 'request.body.items.2.symbol').",
        inputs: &["path:string"],
        output: "any",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "O(depth_of_path)",
        failure: "returns null if path does not exist",
        safety: "read-only access to injected input",
    },
    CapabilitySpec {
        name: "runtime.publish",
        version: "0.1.0",
        package: "runtime",
        summary: "Publish a named computed value into the current decision's journal entry for inspection.",
        inputs: &["name:string", "value:number|string|bool"],
        output: "null",
        purity: Purity::Effectful,
        deterministic: true,
        effects: &["publish"],
        cost: "O(1)",
        failure: "non-string name, non-finite numeric value, or buffer not initialised",
        safety: "values stored in the per-decision journal only; not user-visible filesystem or network state",
    },
    CapabilitySpec {
        name: "file.exists",
        version: "0.1.0",
        package: "io",
        summary: "Check whether a local path exists.",
        inputs: &["path:string"],
        output: "bool",
        purity: Purity::ReadOnlyEffect,
        deterministic: true,
        effects: &["file_read"],
        cost: "O(1) metadata lookup",
        failure: "path argument is not a string",
        safety: "read-only local filesystem metadata; capsule policy must permit file_read",
    },
    CapabilitySpec {
        name: "file.readText",
        version: "0.1.0",
        package: "io",
        summary: "Read a UTF-8 text file from the local filesystem.",
        inputs: &["path:string"],
        output: "string",
        purity: Purity::ReadOnlyEffect,
        deterministic: true,
        effects: &["file_read"],
        cost: "O(file_size), capped at 1 MiB",
        failure: "missing file, non-UTF-8 data, or file exceeds size cap",
        safety: "read-only local filesystem access; capsule policy must permit file_read",
    },
    CapabilitySpec {
        name: "file.writeText",
        version: "0.1.0",
        package: "io",
        summary: "Write UTF-8 text to a local filesystem path.",
        inputs: &["path:string", "contents:string"],
        output: "bool",
        purity: Purity::Effectful,
        deterministic: false,
        effects: &["file_write"],
        cost: "O(contents_size), capped at 1 MiB",
        failure: "write denied, parent missing, or contents exceed cap",
        safety: "effectful local filesystem write; capsule policy must permit file_write",
    },
    CapabilitySpec {
        name: "http.get",
        version: "0.1.0",
        package: "net",
        summary: "Fetch a URL and return the response body as UTF-8 text.",
        inputs: &["url:string"],
        output: "string",
        purity: Purity::ReadOnlyEffect,
        deterministic: false,
        effects: &["network"],
        cost: "network request, 10 second timeout, 1 MiB response cap",
        failure: "invalid URL, request failure, non-success HTTP status, or non-UTF-8 body",
        safety: "outbound network read; capsule policy must permit network",
    },
    CapabilitySpec {
        name: "http.post",
        version: "0.1.0",
        package: "net",
        summary: "POST a UTF-8 body to a URL and return the response body as UTF-8 text.",
        inputs: &["url:string", "body:string", "content_type:string"],
        output: "string",
        purity: Purity::Effectful,
        deterministic: false,
        effects: &["network"],
        cost: "network request, 10 second timeout, 1 MiB request/response cap",
        failure: "invalid URL, request failure, non-success HTTP status, or body exceeds cap",
        safety: "outbound network write; capsule policy must permit network",
    },
    CapabilitySpec {
        name: "json.get",
        version: "0.1.0",
        package: "data",
        summary: "Read a dotted path from a JSON string.",
        inputs: &["json:string", "path:string"],
        output: "any primitive, array, or compact JSON string for objects",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "O(json_size + path_depth)",
        failure: "invalid JSON or missing path",
        safety: "pure parser kernel",
    },
    CapabilitySpec {
        name: "json.has",
        version: "0.1.0",
        package: "data",
        summary: "Return whether a dotted path exists in a JSON string.",
        inputs: &["json:string", "path:string"],
        output: "bool",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "O(json_size + path_depth)",
        failure: "invalid JSON",
        safety: "pure parser kernel",
    },
    CapabilitySpec {
        name: "json.len",
        version: "0.1.0",
        package: "data",
        summary: "Return the length of an array, object, or string at a JSON path.",
        inputs: &["json:string", "path:string"],
        output: "int",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "O(json_size + path_depth)",
        failure: "invalid JSON, missing path, or value has no length",
        safety: "pure parser kernel",
    },
    CapabilitySpec {
        name: "sql.sqliteQuery",
        version: "0.1.0",
        package: "data",
        summary: "Run a read-only SQLite SELECT/WITH/PRAGMA query and return rows.",
        inputs: &["database_path:string", "sql:string"],
        output: "array<array<any>>, capped at 1000 rows",
        purity: Purity::ReadOnlyEffect,
        deterministic: true,
        effects: &["file_read"],
        cost: "SQLite query cost, capped at 1000 returned rows",
        failure: "database missing, SQL invalid, or query is not read-only",
        safety: "read-only SQLite connection; rejects mutating SQL; capsule policy must permit file_read",
    },
    CapabilitySpec {
        name: "stats.mean",
        version: "0.1.0",
        package: "math",
        summary: "Arithmetic mean of a numeric array.",
        inputs: &["values:array<number>"],
        output: "number",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "O(n)",
        failure: "empty or non-numeric array",
        safety: "pure numeric kernel",
    },
    CapabilitySpec {
        name: "stats.stdDev",
        version: "0.1.0",
        package: "math",
        summary: "Population standard deviation of a numeric array.",
        inputs: &["values:array<number>"],
        output: "number",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "O(n)",
        failure: "empty or non-numeric array",
        safety: "pure numeric kernel",
    },
    CapabilitySpec {
        name: "stats.min",
        version: "0.1.0",
        package: "math",
        summary: "Minimum value in a numeric array.",
        inputs: &["values:array<number>"],
        output: "number",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "O(n)",
        failure: "empty or non-numeric array",
        safety: "pure numeric kernel",
    },
    CapabilitySpec {
        name: "stats.max",
        version: "0.1.0",
        package: "math",
        summary: "Maximum value in a numeric array.",
        inputs: &["values:array<number>"],
        output: "number",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "O(n)",
        failure: "empty or non-numeric array",
        safety: "pure numeric kernel",
    },
    CapabilitySpec {
        name: "stats.percentile",
        version: "0.1.0",
        package: "math",
        summary: "Interpolated percentile of a numeric array.",
        inputs: &["values:array<number>", "p:number[0..100]"],
        output: "number",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "O(n log n)",
        failure: "empty array, invalid percentile, or non-numeric input",
        safety: "pure numeric kernel",
    },
    CapabilitySpec {
        name: "series.ewmaForecast",
        version: "0.1.0",
        package: "math",
        summary: "One-step exponential weighted moving average forecast.",
        inputs: &["values:array<number>", "alpha:number[0..1]"],
        output: "number",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "O(n)",
        failure: "empty array, invalid alpha, or non-numeric input",
        safety: "pure time-series kernel",
    },
    CapabilitySpec {
        name: "ops.autoScaleRecommend",
        version: "0.1.0",
        package: "ops",
        summary: "Recommend instance count from predicted load and per-instance target capacity.",
        inputs: &["predicted_load:number", "target_per_instance:number", "min_instances:int", "max_instances:int"],
        output: "int",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "O(1)",
        failure: "invalid numeric input, non-positive capacity, or min > max",
        safety: "pure decision helper; caller owns actual infrastructure changes",
    },
    CapabilitySpec {
        name: "comb.apTuples",
        version: "0.1.0",
        package: "comb",
        summary: "Enumerate k-term arithmetic progressions in {1..n}.",
        inputs: &["n:int", "k:int"],
        output: "array<array<int>>",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "O(number_of_APs * k)",
        failure: "n or k outside bounded proof-lab limits",
        safety: "pure finite combinatorics kernel; output capped to avoid accidental blowups",
    },
    CapabilitySpec {
        name: "comb.isGoodColoring",
        version: "0.1.0",
        package: "comb",
        summary: "Check whether a coloring has no monochromatic or rainbow k-term AP.",
        inputs: &["colors:array<int>", "k:int"],
        output: "bool",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "O(number_of_APs * k)",
        failure: "empty coloring, invalid k, or non-integer colors",
        safety: "pure finite combinatorics checker",
    },
    CapabilitySpec {
        name: "comb.badAp",
        version: "0.1.0",
        package: "comb",
        summary: "Return the first monochromatic or rainbow k-term AP violation in a coloring.",
        inputs: &["colors:array<int>", "k:int"],
        output: "array",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "O(number_of_APs * k)",
        failure: "empty coloring, invalid k, or non-integer colors",
        safety: "pure finite combinatorics checker",
    },
    CapabilitySpec {
        name: "comb.goodColoringWitness",
        version: "0.1.0",
        package: "comb",
        summary: "Search for a coloring with no monochromatic or rainbow k-term AP.",
        inputs: &["n:int", "k:int", "node_limit:int"],
        output: "array",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "exponential search bounded by node_limit",
        failure: "n, k, or node_limit outside bounded proof-lab limits",
        safety: "pure bounded search; inconclusive is returned instead of overclaiming",
    },
    CapabilitySpec {
        name: "comb.hasThreeDistinct4ApColoring",
        version: "0.1.0",
        package: "comb",
        summary: "Check whether every 4-term AP in a coloring has at least three distinct colors.",
        inputs: &["colors:array<int>"],
        output: "bool",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "O(number_of_4_APs)",
        failure: "empty coloring or non-integer colors",
        safety: "pure finite combinatorics checker",
    },
    CapabilitySpec {
        name: "comb.badThreeDistinct4Ap",
        version: "0.1.0",
        package: "comb",
        summary: "Return the first 4-term AP with fewer than three distinct colors.",
        inputs: &["colors:array<int>"],
        output: "array",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "O(number_of_4_APs)",
        failure: "empty coloring or non-integer colors",
        safety: "pure finite combinatorics checker",
    },
    CapabilitySpec {
        name: "comb.threeDistinct4ApWitness",
        version: "0.1.0",
        package: "comb",
        summary: "Search for an Erdos #160 coloring witness with the DFS backend.",
        inputs: &["n:int", "max_colors:int", "node_limit:int"],
        output: "array",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "exponential search bounded by node_limit",
        failure: "n, max_colors, or node_limit outside bounded proof-lab limits",
        safety: "pure bounded search; inconclusive is returned instead of overclaiming",
    },
    CapabilitySpec {
        name: "comb.threeDistinct4ApSatWitness",
        version: "0.1.0",
        package: "comb",
        summary: "Encode Erdos #160 as CNF and run a bounded DPLL SAT search.",
        inputs: &["n:int", "max_colors:int", "node_limit:int"],
        output: "array",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "CNF + exponential DPLL search bounded by node_limit",
        failure: "n, max_colors, or node_limit outside bounded proof-lab limits",
        safety: "pure bounded search; SAT exhaustion is replayable evidence, not a formal DRAT/LRAT proof",
    },
    CapabilitySpec {
        name: "nav.norm3",
        version: "1.0.0",
        package: "nav",
        summary: "Euclidean norm of a 3D vector.",
        inputs: &["x:number", "y:number", "z:number"],
        output: "number",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "O(1)",
        failure: "non-finite or non-numeric input",
        safety: "pure numeric kernel",
    },
    CapabilitySpec {
        name: "nav.distance3",
        version: "1.0.0",
        package: "nav",
        summary: "Euclidean distance between two 3D positions.",
        inputs: &["x:number", "y:number", "z:number", "rx:number", "ry:number", "rz:number"],
        output: "number",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "O(1)",
        failure: "non-finite or non-numeric input",
        safety: "pure numeric kernel",
    },
    CapabilitySpec {
        name: "nav.dot3",
        version: "1.0.0",
        package: "nav",
        summary: "Dot product of two 3D vectors.",
        inputs: &["ax:number", "ay:number", "az:number", "bx:number", "by:number", "bz:number"],
        output: "number",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "O(1)",
        failure: "non-finite or non-numeric input",
        safety: "pure numeric kernel",
    },
    CapabilitySpec {
        name: "nav.radialVelocity",
        version: "1.0.0",
        package: "nav",
        summary: "Radial velocity component of a state vector.",
        inputs: &["x:number", "y:number", "z:number", "vx:number", "vy:number", "vz:number"],
        output: "number",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "O(1)",
        failure: "zero position vector or invalid numeric input",
        safety: "pure numeric kernel",
    },
    CapabilitySpec {
        name: "nav.ephemerisState",
        version: "1.0.0",
        package: "nav",
        summary: "Read a local ephemeris table and interpolate a 6D state vector.",
        inputs: &["path:string", "body:string", "et:number"],
        output: "array<number>[6]",
        purity: Purity::ReadOnlyEffect,
        deterministic: true,
        effects: &["file_read"],
        cost: "O(rows_in_ephemeris_file)",
        failure: "file missing, body mismatch, invalid rows, or time outside coverage",
        safety: "read-only local file access; capsule policy must permit file_read",
    },
    CapabilitySpec {
        name: "nav.horizonsVectors",
        version: "1.0.0",
        package: "nav",
        summary: "Fetch geometric heliocentric state vectors from NASA/JPL Horizons.",
        inputs: &["body:string", "start:string", "stop:string", "step_days:number"],
        output: "flat array [jd,x,y,z,vx,vy,vz,...] in AU and AU/day",
        purity: Purity::ReadOnlyEffect,
        deterministic: false,
        effects: &["network"],
        cost: "NASA/JPL Horizons HTTPS request, 10 second timeout, 1 MiB response cap",
        failure: "network error, Horizons error payload, unsupported body/date/step, or parse failure",
        safety: "outbound request to NASA/JPL Horizons; capsule policy must permit network and host allowlist",
    },
    CapabilitySpec {
        name: "astro.lambertSolve",
        version: "0.1.0",
        package: "astro",
        summary: "Solve the 3D Lambert transfer problem and return departure/arrival velocity vectors.",
        inputs: &[
            "r1x:number", "r1y:number", "r1z:number",
            "r2x:number", "r2y:number", "r2z:number",
            "tof_days:number", "mu:number",
        ],
        output: "array<number>[7] = [v1x,v1y,v1z,v2x,v2y,v2z,status]",
        purity: Purity::Pure,
        deterministic: true,
        effects: &[],
        cost: "iterative numeric solve, bounded by Rust kernel",
        failure: "status=0 on invalid geometry, impossible transfer, or non-convergence",
        safety: "pure numeric kernel; no panics; returns status",
    },
];

pub fn get(name: &str) -> Option<&'static CapabilitySpec> {
    REGISTRY.iter().find(|spec| spec.name == name)
}

pub fn names() -> Vec<&'static str> {
    REGISTRY.iter().map(|spec| spec.name).collect()
}

pub fn json_catalog() -> String {
    let mut out = String::new();
    out.push_str("[\n");
    for (i, spec) in REGISTRY.iter().enumerate() {
        out.push_str(&spec_json(spec, 2));
        if i < REGISTRY.len() - 1 {
            out.push(',');
        }
        out.push('\n');
    }
    out.push(']');
    out
}

pub fn spec_json(spec: &CapabilitySpec, indent: usize) -> String {
    let pad = " ".repeat(indent);
    let pad2 = " ".repeat(indent + 2);
    format!(
        "{pad}{{\n\
{pad2}\"name\": \"{}\",\n\
{pad2}\"version\": \"{}\",\n\
{pad2}\"package\": \"{}\",\n\
{pad2}\"summary\": \"{}\",\n\
{pad2}\"inputs\": [{}],\n\
{pad2}\"output\": \"{}\",\n\
{pad2}\"purity\": \"{}\",\n\
{pad2}\"deterministic\": {},\n\
{pad2}\"effects\": [{}],\n\
{pad2}\"cost\": \"{}\",\n\
{pad2}\"failure\": \"{}\",\n\
{pad2}\"safety\": \"{}\"\n\
{pad}}}",
        esc(spec.name),
        esc(spec.version),
        esc(spec.package),
        esc(spec.summary),
        quoted(spec.inputs).join(", "),
        esc(spec.output),
        match spec.purity {
            Purity::Pure => "pure",
            Purity::ReadOnlyEffect => "read_only_effect",
            Purity::Effectful => "effectful",
        },
        if spec.deterministic { "true" } else { "false" },
        quoted(spec.effects).join(", "),
        esc(spec.cost),
        esc(spec.failure),
        esc(spec.safety),
    )
}

fn quoted(items: &[&str]) -> Vec<String> {
    items.iter().map(|s| format!("\"{}\"", esc(s))).collect()
}

fn esc(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
