from typing import Any, Mapping, Optional, Sequence

class SyntraError(RuntimeError): ...

class Decision:
    decision_id: str
    action: str
    action_index: int
    probability: float
    ranking: list[tuple[str, float]]
    model_version: int
    @property
    def id(self) -> str: ...

class NativeDecider:
    def __init__(
        self, url: str, token: str, tenant: str, job: str, capsule: str, max_queue: int = ...
    ) -> None: ...
    def decide(
        self,
        context: Optional[Mapping[str, Any]] = ...,
        actions: Optional[Sequence[Mapping[str, Any]]] = ...,
        exclude: Optional[Sequence[str]] = ...,
        baseline: Optional[str] = ...,
    ) -> Decision: ...
    def reward(
        self,
        decision_id: str,
        reward: float,
        idempotency_key: Optional[str] = ...,
        detail: Optional[Mapping[str, Any]] = ...,
    ) -> None: ...
    def flush(self) -> dict: ...
    def sync(self) -> bool: ...
    def start_background(self, interval: float) -> None: ...
    def close(self) -> dict: ...
    @property
    def model_version(self) -> int: ...
    @property
    def model_tag(self) -> str: ...
    @property
    def pending(self) -> int: ...
