/**
 * Local evaluation: decide in-process, learn on the server.
 *
 * A `LocalDecider` keeps a copy of a capsule's published model and decides
 * with the Rust decision core compiled to WebAssembly, the code the server
 * runs, so a decision takes microseconds, needs no network, and keeps
 * working through a server outage with the last model it synced.
 * Decisions and rewards are queued and uploaded in batches
 * (`decisions:batch`, then `rewards:batch`). The server replays every
 * uploaded decision against the same published model, input and seed,
 * stores it only if the eligible set, the chosen action and every
 * probability match, and learns from its rewards as if it had served it.
 *
 * ```ts
 * const router = await LocalDecider.connect({ url, token, tenant: "acme", job: "prod", capsule: "router" });
 * const d = router.decide({ task: "code", promptTokens: 812 });
 * // ... act on d.action, observe the outcome ...
 * router.reward(d.decisionId, 0.8);
 * await router.close(); // uploads what is still queued
 * ```
 *
 * This mirrors the Rust `LocalDecider` (`src/client.rs`) and the Python
 * SDK built on it: the same model verification, seeds, decision ids,
 * upload items, batching order and requeueing of retryable refusals. It
 * differs from them in four ways. Upload requests stay under the server's
 * 4 MiB body limit as well as 1000 items, and an event too large to upload
 * at all is dropped and reported instead of blocking the queue. A model
 * whose capsule has a feature program is refused, because the server
 * refuses its uploads. The decision is made from the exact JSON text that
 * is uploaded, so the server parses the numbers the decision saw. And
 * `pending` counts the events a running flush is sending.
 */

import { SyntraClient } from "./client.ts";
import type { SyntraClientOptions } from "./client.ts";
import { loadCore } from "./core.ts";
import type { WasmSource } from "./core.ts";
import { SyntraError } from "./errors.ts";
import type {
  Action,
  Context,
  DecisionUploadResponse,
  RankedAction,
  RewardOptions,
  RewardUploadItem,
  RewardUploadResponse,
  UploadInput,
  UploadedDecision,
} from "./types.ts";
// Generated by `npm run build:wasm` from wasm/src/lib.rs.
import { Model, fixedSeed } from "./wasm/syntra_wasm.js";

/** Most items one `uploadDecisions` or `uploadRewards` call may carry. */
export const MAX_UPLOAD_ITEMS = 4096;
/** Largest request body the server reads (`MAX_BODY_BYTES`). */
const MAX_UPLOAD_BYTES = 4 * 1024 * 1024;
/** Items per upload request, as in the Rust client. */
const UPLOAD_CHUNK = 1000;
/** Bytes per upload request, leaving room for the `{"decisions":[...]}` envelope. */
const UPLOAD_CHUNK_BYTES = MAX_UPLOAD_BYTES - 4096;
const DEFAULT_MAX_QUEUE = 100_000;
const DEFAULT_SYNC_INTERVAL_MS = 1000;
/** Refusal messages kept in a `FlushReport`. */
const MAX_REPORTED_ERRORS = 10;
/** Fixed-seed draws are numbered by a wrapping u64 counter, as in `src/client.rs`. */
const U64_MAX = (1n << 64n) - 1n;

export interface LocalDecideOptions {
  /** Actions for this call only, replacing the spec's. */
  actions?: Action[];
  /** Action ids removed from the eligible set. */
  exclude?: readonly string[] | ReadonlySet<string>;
  /** The incumbent action; required in `baselineExplore` mode. */
  baseline?: string;
}

/** A decision made in-process. */
export interface LocalDecision {
  /** `loc_`, the time in ms (11 hex digits), then 64 random bits (16 hex digits). */
  decisionId: string;
  action: string;
  actionIndex: number;
  probability: number;
  /** Eligible actions, most probable first. */
  ranking: RankedAction[];
  modelVersion: number;
}

/** What one `flush` uploaded. */
export interface FlushReport {
  /** Decisions the server verified and stored, including retried uploads it already had. */
  decisionsAccepted: number;
  /** Decisions refused for good (did not replay, retired model, ...). */
  decisionsRejected: number;
  rewardsApplied: number;
  /** Rewards refused for good (unknown decision, invalid, ...). */
  rewardsFailed: number;
  /** Events the server could not take right now, queued again for the next flush. */
  requeued: number;
  /** The first few refusal messages. */
  errors: string[];
}

export interface LocalDeciderOptions extends SyntraClientOptions {
  /**
   * Upload queued events and fetch a newer model every this many
   * milliseconds in the background (default 1000). The timer does not keep
   * a Node process alive. 0 turns background work off; then call `flush()`
   * and `sync()` yourself.
   */
  syncIntervalMs?: number;
  /**
   * Most decisions plus rewards held for upload (default 100000). At the
   * bound `decide` and `reward` throw instead of dropping events.
   */
  maxQueue?: number;
  /** Called with the errors of background uploads and syncs, which are otherwise dropped. */
  onError?: (error: unknown) => void;
  /**
   * The compiled decision core, for runtimes that cannot load it from the
   * package (see `WasmSource`). Only the first `connect` in a process uses it.
   */
  wasm?: WasmSource;
}

/** The model decisions are made with, and what was read from it once. */
interface Current {
  model: Model;
  tag: string;
  version: number;
  /** `modelVersion` of upload items; absent above 2^53. */
  uploadVersion: number | undefined;
  /** The spec's fixed base seed. */
  seed: bigint | undefined;
  rewardsSum: boolean;
}

/** A decision waiting for upload; its input stays JSON text until then. */
interface PendingDecision {
  decisionId: string;
  tsMs: number;
  tag: string;
  version: number | undefined;
  seed: string;
  /** The exact text the decision was made from. */
  input: string;
  chosenIndex: number;
  chosenId: string;
  probability: number;
  pmf: number[];
  eligible: number[];
}

interface PendingReward {
  decisionId: string;
  reward: number;
  idempotencyKey: string | undefined;
  /** JSON text. */
  detail: string | undefined;
}

/** What `Model.decide` returns (see wasm/src/lib.rs). */
interface Decided {
  chosenIndex: number;
  chosenId: string;
  probability: number;
  pmf: number[];
  eligible: number[];
  ranking: RankedAction[];
  seed: string;
}

/** Decide in-process; learn on the server. */
export class LocalDecider {
  readonly #client: SyntraClient;
  #current: Current;
  #decisions: PendingDecision[] = [];
  #rewards: PendingReward[] = [];
  /** Events a running flush has taken and not yet settled. */
  #inFlight = 0;
  readonly #maxQueue: number;
  /** Draw counter for capsules whose spec fixes a seed. */
  #seedCounter = 0n;
  readonly #random = new RandomBits();
  /** The last decision time and its id prefix, formatted once per millisecond. */
  #idTime = -1;
  #idPrefix = "";
  #flushing: Promise<unknown> = Promise.resolve();
  readonly #intervalMs: number;
  readonly #onError: ((error: unknown) => void) | undefined;
  #timer: ReturnType<typeof setTimeout> | undefined;
  #tick: Promise<void> | undefined;
  #closed = false;

  private constructor(client: SyntraClient, current: Current, options: LocalDeciderOptions) {
    this.#client = client;
    this.#current = current;
    this.#maxQueue = Math.max(1, Math.floor(options.maxQueue ?? DEFAULT_MAX_QUEUE));
    this.#intervalMs = options.syncIntervalMs ?? DEFAULT_SYNC_INTERVAL_MS;
    this.#onError = options.onError;
    this.#schedule();
  }

  /**
   * Load the decision core (once per process), fetch the capsule's
   * published model, and start background uploads unless
   * `syncIntervalMs` is 0.
   */
  static async connect(options: LocalDeciderOptions): Promise<LocalDecider> {
    const { maxQueue, syncIntervalMs } = options;
    if (maxQueue !== undefined && (typeof maxQueue !== "number" || !(maxQueue >= 1))) {
      throw new TypeError("maxQueue must be a number >= 1");
    }
    if (
      syncIntervalMs !== undefined &&
      (typeof syncIntervalMs !== "number" || !Number.isFinite(syncIntervalMs) || syncIntervalMs < 0)
    ) {
      throw new TypeError("syncIntervalMs must be a finite number >= 0");
    }
    const client = new SyntraClient(options);
    const [, text] = await Promise.all([loadCore(options.wasm), client.modelText()]);
    if (text === null) throw new SyntraError("model: the server returned no model");
    return new LocalDecider(client, restore(text), options);
  }

  /** Version of the model decisions are made with. */
  get modelVersion(): number {
    return this.#current.version;
  }

  /** The server's tag for that model; uploaded decisions carry it. */
  get modelTag(): string {
    return this.#current.tag;
  }

  /** Decisions and rewards not yet uploaded, including those a running flush is sending. */
  get pending(): number {
    return this.#decisions.length + this.#rewards.length + this.#inFlight;
  }

  toString(): string {
    return `LocalDecider(${this.#client.url} ${this.#client.tenant}/${this.#client.job}/${this.#client.capsule})`;
  }

  /**
   * Choose an action for `context` with the synced model. The call is
   * synchronous and uses no network. It throws a `SyntraError` when the
   * upload queue is full, and for a request the server would refuse, with
   * the server's message: an unknown action id, a context that is not an
   * object, a number too large for a 32-bit float.
   */
  decide(context?: Context | null, options: LocalDecideOptions = {}): LocalDecision {
    this.#open();
    this.#room();
    const input: UploadInput = { context: context ?? {} };
    if (options.actions !== undefined) input.actions = options.actions;
    if (typeof options.exclude === "string") {
      throw new TypeError("exclude must be a list of action ids, not a string");
    }
    if (options.exclude !== undefined) {
      const excluded = Array.from(options.exclude);
      if (excluded.length > 0) input.excludedActions = excluded;
    }
    if (options.baseline !== undefined) input.baselineAction = options.baseline;
    // The decision is made from this text and the upload sends it again,
    // so later changes to the caller's objects cannot reach the upload and
    // the server parses exactly what the decision saw.
    const text = JSON.stringify(input);

    const current = this.#current;
    let seed: bigint;
    if (current.seed !== undefined) {
      // A capsule with a fixed seed gets reproducible local draws too.
      seed = fixedSeed(current.seed, this.#seedCounter);
      this.#seedCounter = (this.#seedCounter + 1n) & U64_MAX;
    } else {
      seed = this.#random.u64();
    }
    let d: Decided;
    try {
      d = JSON.parse(current.model.decide(text, seed)) as Decided;
    } catch (err) {
      throw new SyntraError(err instanceof Error ? err.message : String(err), { cause: err });
    }
    const tsMs = Date.now();
    if (tsMs !== this.#idTime) {
      this.#idTime = tsMs;
      this.#idPrefix = `loc_${Math.max(0, tsMs).toString(16).padStart(11, "0")}`;
    }
    const decisionId = this.#idPrefix + this.#random.hex();
    this.#decisions.push({
      decisionId,
      tsMs,
      tag: current.tag,
      version: current.uploadVersion,
      seed: d.seed,
      input: text,
      chosenIndex: d.chosenIndex,
      chosenId: d.chosenId,
      probability: d.probability,
      pmf: d.pmf,
      eligible: d.eligible,
    });
    return {
      decisionId,
      action: d.chosenId,
      actionIndex: d.chosenIndex,
      probability: d.probability,
      ranking: d.ranking,
      modelVersion: current.version,
    };
  }

  /**
   * Queue the outcome of a decision made here or on the server. It is
   * uploaded after the decisions queued before it.
   */
  reward(decisionId: string, value: number, options: Omit<RewardOptions, "durable"> = {}): void {
    this.#open();
    if (typeof decisionId !== "string" || decisionId === "") {
      throw new TypeError("decisionId must be a non-empty string");
    }
    if (typeof value !== "number" || !Number.isFinite(value)) {
      throw new TypeError("reward must be a finite number");
    }
    let key = options.idempotencyKey;
    if (key !== undefined && (typeof key !== "string" || key === "" || key.includes("\0") || utf8Length(key) > 256)) {
      throw new TypeError("idempotencyKey must be 1-256 bytes with no NUL");
    }
    // Under `sum` every reward counts, so each gets a key now: a flush
    // retried after a lost response must not count it twice. (Under
    // `first` the server keys rewards by decision id.)
    if (key === undefined && this.#current.rewardsSum) key = `${decisionId}:${this.#random.hex()}`;
    const detail = options.detail === undefined ? undefined : JSON.stringify(options.detail);
    this.#room();
    this.#rewards.push({ decisionId, reward: value, idempotencyKey: key, detail });
  }

  /**
   * Upload queued decisions, then queued rewards. One flush runs at a time;
   * a call made during another waits for it. On a transport or HTTP error
   * the events stay queued and the error is thrown; events the server was
   * too busy to take are queued again and counted in `requeued`.
   */
  flush(): Promise<FlushReport> {
    const run = this.#flushing.then(() => this.#flushOnce());
    this.#flushing = run.catch(() => undefined);
    return run;
  }

  /** Fetch the server's current published model if it differs; true when the model changed. */
  async sync(): Promise<boolean> {
    this.#open();
    const text = await this.#client.modelText({ ifNoneMatch: this.#current.tag });
    if (text === null) return false;
    const next = restore(text);
    if (this.#closed || next.tag === this.#current.tag) {
      next.model.free();
      if (this.#closed) throw closedError();
      return false;
    }
    const previous = this.#current;
    this.#current = next;
    previous.model.free();
    return true;
  }

  /**
   * Stop background work, then upload what is still queued. Afterwards
   * `decide`, `reward` and `sync` throw; `flush` may be called again if
   * this one failed.
   */
  async close(): Promise<FlushReport> {
    if (!this.#closed) {
      this.#closed = true;
      if (this.#timer !== undefined) clearTimeout(this.#timer);
      this.#timer = undefined;
      await this.#tick;
      this.#current.model.free();
    }
    return this.flush();
  }

  // ── Internals ─────────────────────────────────────────────────────────

  #open(): void {
    if (this.#closed) throw closedError();
  }

  #room(): void {
    if (this.pending >= this.#maxQueue) {
      throw new SyntraError("upload queue is full; call flush() or raise maxQueue");
    }
  }

  #schedule(): void {
    if (this.#closed || this.#intervalMs === 0) return;
    const timer = setTimeout(() => {
      this.#timer = undefined;
      this.#tick = this.#background().finally(() => {
        this.#tick = undefined;
        this.#schedule();
      });
    }, this.#intervalMs);
    // Node and Bun: do not keep the process alive for this timer.
    const handle = timer as unknown as { unref?: () => void };
    if (typeof handle === "object" && handle !== null && typeof handle.unref === "function") handle.unref();
    this.#timer = timer;
  }

  async #background(): Promise<void> {
    try {
      if (this.pending > 0) await this.flush();
    } catch (err) {
      this.#report(err);
    }
    try {
      if (!this.#closed) await this.sync();
    } catch (err) {
      // A sync that finds the decider closed has nothing to report.
      if (!this.#closed) this.#report(err);
    }
  }

  #report(err: unknown): void {
    try {
      this.#onError?.(err);
    } catch {
      // A throwing error handler must not stop the background work.
    }
  }

  async #flushOnce(): Promise<FlushReport> {
    // Rewards and decisions are taken together (a reward is always queued
    // after its decision), and decisions upload first, so a reward never
    // reaches the server ahead of its decision.
    const rewards = this.#rewards;
    const decisions = this.#decisions;
    this.#rewards = [];
    this.#decisions = [];
    this.#inFlight = rewards.length + decisions.length;
    const report: FlushReport = {
      decisionsAccepted: 0,
      decisionsRejected: 0,
      rewardsApplied: 0,
      rewardsFailed: 0,
      requeued: 0,
      errors: [],
    };
    const note = (error: unknown): void => {
      if (report.errors.length < MAX_REPORTED_ERRORS) {
        report.errors.push(typeof error === "string" ? error : "rejected");
      }
    };
    try {
      const retryDecisions: PendingDecision[] = [];
      let next = 0;
      while (next < decisions.length) {
        const chunk = takeChunk(decisions, next, decisionItem, (d, bytes) => {
          report.decisionsRejected += 1;
          note(`decision ${d.decisionId} is ${bytes} bytes, more than the server's request limit`);
        });
        next = chunk.end;
        if (chunk.pending.length === 0) continue;
        let answer: DecisionUploadResponse;
        try {
          answer = await this.#client.uploadDecisions(chunk.items);
        } catch (err) {
          this.#requeue([...retryDecisions, ...chunk.pending, ...decisions.slice(next)], rewards);
          throw err;
        }
        report.decisionsAccepted += answer.accepted ?? 0;
        for (const r of answer.rejected ?? []) {
          const item = Number.isInteger(r.index) ? chunk.pending[r.index] : undefined;
          if (r.retryable === true && item !== undefined) {
            retryDecisions.push(item);
          } else {
            report.decisionsRejected += 1;
            note(r.error);
          }
        }
      }
      // Rewards wait while any decision is waiting: a reward uploaded
      // ahead of its decision would be refused as unknown.
      if (retryDecisions.length > 0) {
        report.requeued = retryDecisions.length + rewards.length;
        this.#requeue(retryDecisions, rewards);
        return report;
      }

      const retryRewards: PendingReward[] = [];
      next = 0;
      while (next < rewards.length) {
        const chunk = takeChunk(rewards, next, rewardItem, (r, bytes) => {
          report.rewardsFailed += 1;
          note(`reward for ${r.decisionId} is ${bytes} bytes, more than the server's request limit`);
        });
        next = chunk.end;
        if (chunk.pending.length === 0) continue;
        let answer: RewardUploadResponse;
        try {
          answer = await this.#client.uploadRewards(chunk.items);
        } catch (err) {
          this.#requeue([], [...retryRewards, ...chunk.pending, ...rewards.slice(next)]);
          throw err;
        }
        const results = answer.results ?? [];
        for (let k = 0; k < chunk.pending.length; k++) {
          const r = results[k];
          if (r?.ok === true) {
            report.rewardsApplied += 1;
          } else if (r?.status === 503) {
            retryRewards.push(chunk.pending[k] as PendingReward);
          } else {
            report.rewardsFailed += 1;
            note(r === undefined ? "the server returned no result for this reward" : r.error);
          }
        }
      }
      report.requeued = retryRewards.length;
      this.#requeue([], retryRewards);
      return report;
    } finally {
      this.#inFlight = 0;
    }
  }

  /** Put events back at the front of the queues, in their original order. */
  #requeue(decisions: PendingDecision[], rewards: PendingReward[]): void {
    if (decisions.length > 0) this.#decisions = decisions.concat(this.#decisions);
    if (rewards.length > 0) this.#rewards = rewards.concat(this.#rewards);
  }
}

/** Build a model from the model endpoint's response text. */
function restore(text: string): Current {
  let model: Model;
  try {
    model = new Model(text);
  } catch (err) {
    throw new SyntraError(err instanceof Error ? err.message : String(err), { cause: err });
  }
  const version = model.version;
  return {
    model,
    tag: model.tag,
    version: Number(version),
    uploadVersion: version <= BigInt(Number.MAX_SAFE_INTEGER) ? Number(version) : undefined,
    seed: model.seed,
    rewardsSum: model.rewardsSum,
  };
}

function decisionItem(d: PendingDecision): { item: UploadedDecision; bytes: number } {
  const item: UploadedDecision = {
    decisionId: d.decisionId,
    tsMs: d.tsMs,
    modelTag: d.tag,
    seed: d.seed,
    input: {},
    chosenIndex: d.chosenIndex,
    chosenId: d.chosenId,
    probability: d.probability,
    pmf: d.pmf,
    eligible: d.eligible,
  };
  if (d.version !== undefined) item.modelVersion = d.version;
  // Serialized with a stand-in input, whose size is then swapped for the
  // input's: the input is the bulk of an item.
  const bytes = utf8Length(JSON.stringify(item)) - 2 + utf8Length(d.input);
  // JSON.stringify(JSON.parse(text)) gives back `text` for any text
  // JSON.stringify produced, so the server parses what was decided on.
  item.input = JSON.parse(d.input) as UploadInput;
  return { item, bytes };
}

function rewardItem(r: PendingReward): { item: RewardUploadItem; bytes: number } {
  const item: RewardUploadItem = { decisionId: r.decisionId, reward: r.reward };
  if (r.idempotencyKey !== undefined) item.idempotencyKey = r.idempotencyKey;
  let bytes = utf8Length(JSON.stringify(item));
  if (r.detail !== undefined) {
    item.detail = JSON.parse(r.detail) as unknown;
    bytes += utf8Length(r.detail) + ',"detail":'.length;
  }
  return { item, bytes };
}

/**
 * The next upload request's worth of events from `from`: at most
 * `UPLOAD_CHUNK` items and `UPLOAD_CHUNK_BYTES` bytes. An event too large
 * to upload on its own is passed to `tooLarge` and dropped.
 */
function takeChunk<P, I>(
  events: P[],
  from: number,
  toItem: (event: P) => { item: I; bytes: number },
  tooLarge: (event: P, bytes: number) => void,
): { pending: P[]; items: I[]; end: number } {
  const pending: P[] = [];
  const items: I[] = [];
  let total = 0;
  let end = from;
  while (end < events.length && items.length < UPLOAD_CHUNK) {
    const event = events[end];
    const { item, bytes } = toItem(event);
    if (bytes > UPLOAD_CHUNK_BYTES) {
      tooLarge(event, bytes);
      end += 1;
      continue;
    }
    // One byte for the comma between items.
    if (items.length > 0 && total + bytes + 1 > UPLOAD_CHUNK_BYTES) break;
    total += bytes + 1;
    pending.push(event);
    items.push(item);
    end += 1;
  }
  return { pending, items, end };
}

/** UTF-8 length of a string, without encoding it. */
function utf8Length(text: string): number {
  let bytes = text.length;
  for (let i = 0; i < text.length; i++) {
    const c = text.charCodeAt(i);
    if (c < 0x80) continue;
    if (c < 0x800) {
      bytes += 1;
    } else if (c >= 0xd800 && c <= 0xdbff && i + 1 < text.length) {
      const d = text.charCodeAt(i + 1);
      // A surrogate pair: two UTF-16 units, four bytes.
      if (d >= 0xdc00 && d <= 0xdfff) {
        bytes += 2;
        i += 1;
        continue;
      }
      bytes += 2;
    } else {
      bytes += 2;
    }
  }
  return bytes;
}

function closedError(): SyntraError {
  return new SyntraError("the LocalDecider is closed");
}

/** Random u64s from the platform CSPRNG, fetched in blocks. */
class RandomBits {
  readonly #block = new BigUint64Array(256);
  #next = this.#block.length;

  u64(): bigint {
    if (this.#next === this.#block.length) {
      crypto.getRandomValues(this.#block);
      this.#next = 0;
    }
    return this.#block[this.#next++] as bigint;
  }

  /** 64 random bits as 16 hex digits. */
  hex(): string {
    return this.u64().toString(16).padStart(16, "0");
  }
}
