use serde::Deserialize;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

#[derive(Debug, Deserialize)]
struct BanditSpec {
    name: String,
    options: Vec<String>,
    #[serde(default)]
    contexts: Vec<String>,
    #[serde(default)]
    reward: BTreeMap<String, f64>,
}

#[derive(Debug)]
pub struct AuthorResult {
    pub lyc_path: PathBuf,
    pub source_path: Option<PathBuf>,
    pub bytes: usize,
    pub nodes: usize,
    pub edges: usize,
    pub options: usize,
}

pub fn author_yaml_file(
    spec_path: &Path,
    lyc_path: &Path,
    source_path: Option<&Path>,
) -> Result<AuthorResult, String> {
    let yaml = std::fs::read_to_string(spec_path)
        .map_err(|e| format!("cannot read {}: {e}", spec_path.display()))?;
    let source = yaml_to_lycan_source(&yaml)?;
    let graph = compile_source(&source)?;
    let data = graph.to_bytes();

    if let Some(path) = source_path {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| format!("cannot create {}: {e}", parent.display()))?;
        }
        std::fs::write(path, source.as_bytes())
            .map_err(|e| format!("cannot write {}: {e}", path.display()))?;
    }

    if let Some(parent) = lyc_path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("cannot create {}: {e}", parent.display()))?;
    }
    std::fs::write(lyc_path, &data)
        .map_err(|e| format!("cannot write {}: {e}", lyc_path.display()))?;

    Ok(AuthorResult {
        lyc_path: lyc_path.to_path_buf(),
        source_path: source_path.map(Path::to_path_buf),
        bytes: data.len(),
        nodes: graph.nodes.len(),
        edges: graph.edges.len(),
        options: spec_option_count(&yaml)?,
    })
}

pub fn yaml_to_lycan_source(yaml: &str) -> Result<String, String> {
    let spec: BanditSpec =
        serde_yml::from_str(yaml).map_err(|e| format!("invalid authoring YAML: {e}"))?;
    validate_spec(&spec)?;

    let mut out = String::new();
    out.push_str(";; Generated by Syntra YAML authoring.\n");
    out.push_str(";; This is the readable Lycan source for a simple adaptive bandit capsule.\n");
    out.push_str(&format!(";; name: {}\n", comment_text(&spec.name)));
    out.push_str(";; options:\n");
    for (idx, option) in spec.options.iter().enumerate() {
        out.push_str(&format!(";;   {idx}: {}\n", comment_text(option)));
    }
    if !spec.contexts.is_empty() {
        out.push_str(";; contexts:\n");
        for context in &spec.contexts {
            out.push_str(&format!(";;   - {}\n", comment_text(context)));
        }
    }
    if !spec.reward.is_empty() {
        out.push_str(";; reward: weighted sum of normalized outcome metrics\n");
        for (metric, weight) in &spec.reward {
            out.push_str(&format!(";;   {}: {}\n", comment_text(metric), weight));
        }
    }
    out.push('\n');

    for (idx, context) in spec.contexts.iter().enumerate() {
        out.push_str(&format!(
            "($ ctx_{idx} (!cap \"runtime.inputGet\" \"{}\"))\n",
            lycan_string(context)
        ));
    }
    if !spec.contexts.is_empty() {
        out.push('\n');
    }

    out.push_str("(F option_name (idx)\n  ");
    out.push_str(&option_name_expr(&spec.options, 0));
    out.push_str(")\n\n");

    let option_values: Vec<String> = (0..spec.options.len()).map(|i| i.to_string()).collect();
    out.push_str(&format!(
        "($ selected_option (choice {}))\n\n",
        option_values.join(" ")
    ));

    out.push_str(&format!(
        "(!p \"=== Syntra YAML Capsule: {} ===\")\n",
        lycan_string(&spec.name)
    ));
    for (idx, context) in spec.contexts.iter().enumerate() {
        out.push_str(&format!(
            "(!p \"context {}:\" ctx_{idx})\n",
            lycan_string(context)
        ));
    }
    for (idx, option) in spec.options.iter().enumerate() {
        out.push_str(&format!("(!p \"{idx} {}\")\n", lycan_string(option)));
    }
    out.push_str("(!p \"Syntra selected option:\" selected_option)\n");
    out.push_str("(!p \"Syntra selected name:\" (option_name selected_option))\n");
    out.push_str("selected_option\n");

    Ok(out)
}

fn validate_spec(spec: &BanditSpec) -> Result<(), String> {
    if spec.name.trim().is_empty() {
        return Err("name is required".to_string());
    }
    if spec.options.len() < 2 {
        return Err("options must contain at least two entries".to_string());
    }
    for (idx, option) in spec.options.iter().enumerate() {
        if option.trim().is_empty() {
            return Err(format!("options[{idx}] must not be empty"));
        }
    }
    for (idx, context) in spec.contexts.iter().enumerate() {
        if context.trim().is_empty() {
            return Err(format!("contexts[{idx}] must not be empty"));
        }
    }
    for (metric, weight) in &spec.reward {
        if metric.trim().is_empty() {
            return Err("reward metric names must not be empty".to_string());
        }
        if !weight.is_finite() {
            return Err(format!("reward metric {metric} has non-finite weight"));
        }
    }
    Ok(())
}

fn compile_source(source: &str) -> Result<lycan::graph::NeuralGraph, String> {
    let mut lexer = lycan::lexer::Lexer::new(source);
    let tokens = lexer.tokenize().map_err(|e| e.to_string())?;
    let mut parser = lycan::parser::Parser::new(tokens);
    let program = parser.parse_program().map_err(|e| e.to_string())?;
    let compiler = lycan::graph_compiler::GraphCompiler::new();
    Ok(compiler.compile(&program))
}

fn option_name_expr(options: &[String], idx: usize) -> String {
    let current = format!("\"{}\"", lycan_string(&options[idx]));
    if idx + 1 == options.len() {
        current
    } else {
        format!(
            "(? (== idx {idx}) {current} {})",
            option_name_expr(options, idx + 1)
        )
    }
}

fn lycan_string(value: &str) -> String {
    value
        .chars()
        .flat_map(|c| match c {
            '\\' => "\\\\".chars().collect::<Vec<_>>(),
            '"' => "\\\"".chars().collect::<Vec<_>>(),
            '\n' => "\\n".chars().collect::<Vec<_>>(),
            '\r' => "\\r".chars().collect::<Vec<_>>(),
            '\t' => "\\t".chars().collect::<Vec<_>>(),
            c if c.is_control() => ' '.to_string().chars().collect::<Vec<_>>(),
            c => vec![c],
        })
        .collect()
}

fn comment_text(value: &str) -> String {
    value.replace('\n', " ").replace('\r', " ")
}

fn spec_option_count(yaml: &str) -> Result<usize, String> {
    let spec: BanditSpec =
        serde_yml::from_str(yaml).map_err(|e| format!("invalid authoring YAML: {e}"))?;
    Ok(spec.options.len())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn yaml_source_contains_choice_and_contexts() {
        let src = yaml_to_lycan_source(
            r#"
name: llm-router
options:
  - cheap_fast
  - balanced
  - expensive_accurate
contexts:
  - task_type
  - customer_tier
reward:
  quality: 0.6
  latency: -0.2
"#,
        )
        .expect("valid source");

        assert!(src.contains("($ selected_option (choice 0 1 2))"));
        assert!(src.contains("runtime.inputGet"));
        assert!(src.contains("task_type"));
        assert!(compile_source(&src).is_ok());
    }

    #[test]
    fn yaml_requires_two_options() {
        let err = yaml_to_lycan_source(
            r#"
name: bad
options:
  - only
"#,
        )
        .expect_err("must reject single option");
        assert!(err.contains("at least two"));
    }
}
