use std::path::{Path, PathBuf};

use crate::capsule_spec::{AlgorithmKind, CapsuleSpec, NormalizeKind, RewardType};

pub struct CompiledCapsule {
    pub out_dir: PathBuf,
    pub lyc_bytes: usize,
    pub nodes: usize,
    pub edges: usize,
    pub options: usize,
    pub algorithm: AlgorithmKind,
}

pub fn compile_to_dir(spec: &CapsuleSpec, out_dir: &Path) -> Result<CompiledCapsule, String> {
    spec.validate()?;
    std::fs::create_dir_all(out_dir)
        .map_err(|e| format!("cannot create {}: {e}", out_dir.display()))?;

    let source = emit_lycan_source(spec);
    let graph = compile_source(&source)?;
    let lyc_bytes = graph.to_bytes();

    let lyc_path = out_dir.join("program.lyc");
    std::fs::write(&lyc_path, &lyc_bytes)
        .map_err(|e| format!("cannot write {}: {e}", lyc_path.display()))?;

    let lycs_path = out_dir.join("program.lycs");
    std::fs::write(&lycs_path, source.as_bytes())
        .map_err(|e| format!("cannot write {}: {e}", lycs_path.display()))?;

    let resolved = spec.resolved_algorithm();
    let learning_json = build_learning_json(spec, resolved);
    let learning_path = out_dir.join("learning.json");
    std::fs::write(&learning_path, serde_json::to_string_pretty(&learning_json).unwrap().as_bytes())
        .map_err(|e| format!("cannot write {}: {e}", learning_path.display()))?;

    let reward_spec_json = build_reward_spec_json(spec);
    let reward_path = out_dir.join("reward_spec.json");
    std::fs::write(&reward_path, serde_json::to_string_pretty(&reward_spec_json).unwrap().as_bytes())
        .map_err(|e| format!("cannot write {}: {e}", reward_path.display()))?;

    let context_schema = serde_json::json!({ "contexts": spec.contexts });
    let ctx_path = out_dir.join("context_schema.json");
    std::fs::write(&ctx_path, serde_json::to_string_pretty(&context_schema).unwrap().as_bytes())
        .map_err(|e| format!("cannot write {}: {e}", ctx_path.display()))?;

    // Hierarchical bandits sidecar (roadmap.md step 2). Persists the
    // tree spec next to the .lyc so the runtime branch (queued) can
    // load it without re-parsing the original YAML. Graph emission
    // stays single-node (one AdaptiveChoice over the flattened leaf
    // names) — the recursion happens at decide-time in `do_decide`.
    let mut sidecar_paths: Vec<&'static str> = Vec::new();
    if let Some(hier) = &spec.hierarchical_options {
        let hier_path = out_dir.join("hierarchical_spec.json");
        std::fs::write(&hier_path, serde_json::to_string_pretty(&hier.to_json()).unwrap().as_bytes())
            .map_err(|e| format!("cannot write {}: {e}", hier_path.display()))?;
        sidecar_paths.push("hierarchical_spec.json");
    }

    let manifest = serde_json::json!({
        "name": spec.name,
        "version": spec.version,
        "options": spec.options,
        "algorithm": algorithm_name(resolved),
        "rewardType": reward_type_name(spec.reward.kind),
        "componentNames": spec.reward.components.iter().map(|c| c.name.clone()).collect::<Vec<_>>(),
        // Carry sidecar pointers so an operator inspecting the install
        // directory can tell at a glance which optional capabilities are
        // wired. Currently used by hierarchical_spec.json only; future
        // capabilities can append.
        "sidecars": sidecar_paths,
    });
    let manifest_path = out_dir.join("manifest.json");
    std::fs::write(&manifest_path, serde_json::to_string_pretty(&manifest).unwrap().as_bytes())
        .map_err(|e| format!("cannot write {}: {e}", manifest_path.display()))?;

    Ok(CompiledCapsule {
        out_dir: out_dir.to_path_buf(),
        lyc_bytes: lyc_bytes.len(),
        nodes: graph.nodes.len(),
        edges: graph.edges.len(),
        options: spec.options.len(),
        algorithm: resolved,
    })
}

fn emit_lycan_source(spec: &CapsuleSpec) -> String {
    let mut out = String::new();
    out.push_str(";; Generated by Syntra capsule compiler.\n");
    out.push_str(&format!(";; capsule: {}\n", spec.name));
    out.push('\n');

    for (idx, context) in spec.contexts.iter().enumerate() {
        out.push_str(&format!(
            "($ ctx_{idx} (!cap \"runtime.inputGet\" \"{}\"))\n",
            escape_string(context)
        ));
    }
    if !spec.contexts.is_empty() {
        out.push('\n');
    }

    out.push_str("(F option_name (idx)\n  ");
    out.push_str(&option_name_expr(&spec.options, 0));
    out.push_str(")\n\n");

    // 3C: when `decisions: []` is declared, emit one AdaptiveChoice node
    // per decision in topological order so the 5C runtime in Lang's
    // `do_decide` visits them in the order the user declared. The runtime
    // gives each its own meta-bandit selection + per-node candidate-id
    // audit trail; the dependency_map is preserved by the emission order.
    if let Some(decisions) = spec.decisions.as_ref().filter(|d| !d.is_empty()) {
        let order = spec.decision_order();
        let dmap = spec.dependency_map();
        for (idx, dec_name) in order.iter().enumerate() {
            // Find the decision spec by name to get its options.
            let dec = match decisions.iter().find(|d| &d.name == dec_name) {
                Some(d) => d,
                None => continue,
            };
            let opt_indices: Vec<String> = (0..dec.options.len()).map(|i| i.to_string()).collect();
            let parent = dmap.get(&dec_name[..])
                .and_then(|x| x.as_deref())
                .unwrap_or("(root)");
            // Suffix the variable name with the decision index so each one
            // gets its own AdaptiveChoice node in the compiled graph.
            out.push_str(&format!(
                ";; decision[{idx}] name={dec_name} depends_on={parent}\n",
            ));
            out.push_str(&format!(
                "($ selected_{idx} (choice {}))\n",
                opt_indices.join(" "),
            ));
            out.push_str(&format!(
                "(!p \"capsule {}, decision[{idx}={dec_name}]:\" selected_{idx})\n\n",
                escape_string(&spec.name),
            ));
        }
        // Return the LAST decision's chosen index. Consumers wanting all
        // decisions read them from the /decide response's `decisions[]`
        // array (the 5C path populates one entry per AdaptiveChoice node).
        let last = order.len().saturating_sub(1);
        out.push_str(&format!("selected_{last}\n"));
    } else {
        // Default single-decision shape (backward compat with all
        // pre-3C capsules).
        let option_indices: Vec<String> = (0..spec.options.len()).map(|i| i.to_string()).collect();
        out.push_str(&format!(
            "($ selected_option (choice {}))\n\n",
            option_indices.join(" ")
        ));
        out.push_str(&format!(
            "(!p \"capsule {}, option:\" selected_option)\n",
            escape_string(&spec.name)
        ));
        out.push_str("selected_option\n");
    }
    out
}

fn option_name_expr(options: &[String], idx: usize) -> String {
    let cur = format!("\"{}\"", escape_string(&options[idx]));
    if idx + 1 == options.len() {
        cur
    } else {
        format!("(? (== idx {idx}) {cur} {})", option_name_expr(options, idx + 1))
    }
}

fn escape_string(s: &str) -> String {
    s.chars()
        .flat_map(|c| match c {
            '\\' => "\\\\".chars().collect::<Vec<_>>(),
            '"' => "\\\"".chars().collect::<Vec<_>>(),
            '\n' => "\\n".chars().collect::<Vec<_>>(),
            '\r' => "\\r".chars().collect::<Vec<_>>(),
            '\t' => "\\t".chars().collect::<Vec<_>>(),
            c if c.is_control() => ' '.to_string().chars().collect::<Vec<_>>(),
            c => vec![c],
        })
        .collect()
}

fn compile_source(source: &str) -> Result<lycan::graph::NeuralGraph, String> {
    let mut lexer = lycan::lexer::Lexer::new(source);
    let tokens = lexer.tokenize().map_err(|e| e.to_string())?;
    let mut parser = lycan::parser::Parser::new(tokens);
    let program = parser.parse_program().map_err(|e| e.to_string())?;
    let compiler = lycan::graph_compiler::GraphCompiler::new();
    Ok(compiler.compile(&program))
}

fn build_learning_json(spec: &CapsuleSpec, algorithm: AlgorithmKind) -> serde_json::Value {
    let alg_name = match algorithm {
        AlgorithmKind::Auto => "thompson",
        AlgorithmKind::Thompson => "thompson",
        AlgorithmKind::Ucb => "ucb1",
        AlgorithmKind::EpsilonGreedy => "epsilonGreedy",
        AlgorithmKind::Weighted => "simpleWeighted",
    };
    let mut j = serde_json::json!({
        "algorithm": alg_name,
        "safety": {
            "minExploration": spec.learning.min_exploration,
            "selectionMode": match algorithm {
                AlgorithmKind::Weighted => "weighted",
                AlgorithmKind::Thompson | AlgorithmKind::Ucb => "greedy",
                AlgorithmKind::EpsilonGreedy => "epsilonGreedy",
                AlgorithmKind::Auto => "greedy",
            },
        }
    });
    if matches!(algorithm, AlgorithmKind::EpsilonGreedy) {
        j["epsilon"] = serde_json::json!(0.10);
        j["safety"]["selectionEpsilon"] = serde_json::json!(0.10);
    }
    j
}

fn build_reward_spec_json(spec: &CapsuleSpec) -> serde_json::Value {
    let components: Vec<serde_json::Value> = spec.reward.components.iter().map(|c| {
        serde_json::json!({
            "name": c.name,
            "weight": c.weight,
            "normalize": match c.normalize {
                NormalizeKind::Minmax => "minmax",
                NormalizeKind::Budget => "budget",
            },
            "range": c.range,
            "budget": c.budget,
        })
    }).collect();
    serde_json::json!({
        "type": reward_type_name(spec.reward.kind),
        "range": spec.reward.range,
        "components": components,
    })
}

fn algorithm_name(a: AlgorithmKind) -> &'static str {
    match a {
        AlgorithmKind::Auto | AlgorithmKind::Thompson => "thompson",
        AlgorithmKind::Ucb => "ucb",
        AlgorithmKind::EpsilonGreedy => "epsilon_greedy",
        AlgorithmKind::Weighted => "weighted",
    }
}

fn reward_type_name(t: RewardType) -> &'static str {
    match t {
        RewardType::Bernoulli => "bernoulli",
        RewardType::Continuous => "continuous",
        RewardType::SparseContinuous => "sparse_continuous",
    }
}

pub fn compute_reward_from_components(
    reward_spec: &serde_json::Value,
    components: &serde_json::Value,
) -> f64 {
    lycan::learning::compute_reward_from_components(reward_spec, components)
}

#[cfg(test)]
mod tests {
    use super::*;

    const LLM_ROUTER_YAML: &str = r#"
name: llm-router
options: [cheap_fast, balanced, expensive_accurate]
contexts: [task_type, customer_tier]
reward:
  type: continuous
  range: [-1.0, 1.0]
  components:
    - { name: quality,    weight: 0.6,  normalize: minmax, range: [0.0, 1.0] }
    - { name: latency_ms, weight: -0.2, normalize: budget, budget: 2000 }
    - { name: cost_usd,   weight: -0.2, normalize: budget, budget: 0.05 }
"#;

    #[test]
    fn compiles_llm_router_to_directory() {
        let spec = CapsuleSpec::from_yaml(LLM_ROUTER_YAML).unwrap();
        let dir = std::env::temp_dir().join(format!("syntra-cap-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        let result = compile_to_dir(&spec, &dir).unwrap();

        assert!(dir.join("program.lyc").exists());
        assert!(dir.join("program.lycs").exists());
        assert!(dir.join("learning.json").exists());
        assert!(dir.join("reward_spec.json").exists());
        assert!(dir.join("context_schema.json").exists());
        assert!(dir.join("manifest.json").exists());
        assert_eq!(result.options, 3);
        assert_eq!(result.algorithm, AlgorithmKind::Weighted);

        let learning: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(dir.join("learning.json")).unwrap()).unwrap();
        assert_eq!(learning["algorithm"], "simpleWeighted");
        assert_eq!(learning["safety"]["selectionMode"], "weighted");

        let reward_spec: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(dir.join("reward_spec.json")).unwrap()).unwrap();
        assert_eq!(reward_spec["components"].as_array().unwrap().len(), 3);

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn computes_composite_reward() {
        let spec = CapsuleSpec::from_yaml(LLM_ROUTER_YAML).unwrap();
        let reward_spec = build_reward_spec_json(&spec);
        let components = serde_json::json!({
            "quality": 0.85,
            "latency_ms": 1240,
            "cost_usd": 0.018,
        });
        // 0.6 * 0.85 + (-0.2) * (1240/2000) + (-0.2) * (0.018/0.05)
        // = 0.510 - 0.124 - 0.072 = 0.314
        let r = compute_reward_from_components(&reward_spec, &components);
        assert!((r - 0.314).abs() < 1e-6, "got {r}");
    }

    #[test]
    fn bernoulli_capsule_compiles_to_thompson() {
        let y = r#"
name: ab-test
options: [a, b]
reward: { type: bernoulli }
"#;
        let spec = CapsuleSpec::from_yaml(y).unwrap();
        let dir = std::env::temp_dir().join(format!("syntra-cap-bern-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        let result = compile_to_dir(&spec, &dir).unwrap();
        assert_eq!(result.algorithm, AlgorithmKind::Thompson);

        let learning: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(dir.join("learning.json")).unwrap()).unwrap();
        assert_eq!(learning["algorithm"], "thompson");
        assert_eq!(learning["safety"]["selectionMode"], "greedy");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn hierarchical_capsule_emits_sidecar_and_manifest_pointer() {
        // Hierarchical wiring step 2: when a capsule's spec carries
        // `hierarchical_options`, `compile_to_dir` must persist
        // `hierarchical_spec.json` and reference it in `manifest.sidecars`.
        let y = r#"
name: hier-region-routing
options: [us_small, us_medium, eu_small, eu_medium]
reward: { type: continuous, range: [-1, 1] }
hierarchical_options:
  options:
    - name: us
      sub_capsule:
        options: [us_small, us_medium]
        reward: { type: continuous, range: [-1, 1] }
    - name: eu
      sub_capsule:
        options: [eu_small, eu_medium]
        reward: { type: continuous, range: [-1, 1] }
  reward: { type: continuous, range: [-1, 1] }
"#;
        let spec = CapsuleSpec::from_yaml(y).expect("valid hierarchical spec");
        let dir = std::env::temp_dir().join(format!("syntra-cap-hier-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        let result = compile_to_dir(&spec, &dir).expect("compile");
        // Graph emission stays single-node (one AdaptiveChoice over 4 leaves)
        // — recursion will happen at decide-time in the runtime branch.
        assert_eq!(result.options, 4);

        // hierarchical_spec.json sidecar exists.
        let hier_path = dir.join("hierarchical_spec.json");
        assert!(hier_path.exists(), "hierarchical_spec.json must be written");

        // It round-trips through HierarchicalSpec::from_json cleanly.
        let raw = std::fs::read_to_string(&hier_path).unwrap();
        let v: serde_json::Value = serde_json::from_str(&raw).unwrap();
        let reparsed = lycan::hierarchical::HierarchicalSpec::from_json(&v)
            .expect("sidecar round-trips");
        reparsed.validate().expect("sidecar is valid");
        assert_eq!(reparsed.max_depth(), 2);
        assert_eq!(reparsed.count_leaves(), 4);

        // The manifest's `sidecars` array references the new file by name.
        let manifest: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(dir.join("manifest.json")).unwrap()).unwrap();
        let sidecars = manifest["sidecars"].as_array().expect("sidecars array");
        let names: Vec<&str> = sidecars.iter().filter_map(|v| v.as_str()).collect();
        assert!(names.contains(&"hierarchical_spec.json"),
                "manifest.sidecars must reference hierarchical_spec.json, got {names:?}");

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn flat_capsule_omits_hierarchical_sidecar() {
        // The sidecar is purely opt-in. Pre-existing flat capsules don't
        // get a hierarchical_spec.json or a non-empty sidecars list.
        let spec = CapsuleSpec::from_yaml(LLM_ROUTER_YAML).unwrap();
        let dir = std::env::temp_dir().join(format!("syntra-cap-flat-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        compile_to_dir(&spec, &dir).expect("compile");

        assert!(!dir.join("hierarchical_spec.json").exists(),
                "flat capsule must not emit a hierarchical sidecar");
        let manifest: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(dir.join("manifest.json")).unwrap()).unwrap();
        let sidecars = manifest["sidecars"].as_array().expect("sidecars array");
        assert!(sidecars.is_empty(), "flat capsule's sidecars must be empty, got {sidecars:?}");

        let _ = std::fs::remove_dir_all(&dir);
    }
}
